"use client";

import React, { useEffect, useRef, useState } from "react";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Disclaimer } from "@/components/ui/Disclaimer";
import { Icon } from "@/components/ui/Icon";
import { Modal } from "@/components/ui/Modal";
import { ProgressBar } from "@/components/ui/ProgressBar";
import { MOCK_ASSESSMENTS, MOCK_DOCTORS, MOCK_PARENTS } from "@/data/mockDashboard";
import { MOCK_PRODUCTS } from "@/data/mockProducts";
import { RAKTASETU_TESTS } from "@/data/mockBloodTests";
import { BODY_FITNESS_STEPS } from "@/data/bodyQuestions";
import { QUICK_HEART_QUESTIONS, DETAILED_HEART_QUESTIONS } from "@/data/heartQuestions";
import { PCOS_STEPS } from "@/data/pcosQuestions";
import { LEGAL_DOCS } from "@/data/legalDocs";
import { ECGBackground, MagneticWrap, ScoreRing, ShareButtons, TiltCard, track, useMouseParallax, useScrollReveal, useTilt } from "@/components/shared/prototype";
import { LockedModal } from "@/components/auth/LockedModal";
import { ScannerModal } from "@/components/tools/products/ProductScanner";

export const RaktaSetuPage = ({ navigate }) => {
  const [category, setCategory] = useState("all");
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState(null);
  const [compare, setCompare] = useState([]);
  const cats = [{ id: "all", label: "All" }, { id: "cbc", label: "CBC" }, { id: "lipid", label: "Lipids" }, { id: "diabetes", label: "Diabetes" }, { id: "thyroid", label: "Thyroid" }, { id: "fbc", label: "Full body" }, { id: "hormone", label: "Hormones" }];
  const filtered = RAKTASETU_TESTS.filter(t => (category === "all" || t.cat === category) && (t.name + t.lab + t.biomarkers.join(" ")).toLowerCase().includes(query.toLowerCase()));
  const toggleCompare = (id) => setCompare(prev => prev.includes(id) ? prev.filter(x => x !== id) : prev.length >= 3 ? prev : [...prev, id]);
  const compareTests = RAKTASETU_TESTS.filter(t => compare.includes(t.id));
  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 py-12 slide-up">
      <div className="grid lg:grid-cols-[1.05fr_0.95fr] gap-8 items-center mb-10">
        <div><Badge color="red">RaktaSetu</Badge><h1 className="serif text-4xl sm:text-5xl font-medium text-ink mt-4 mb-4 leading-tight">Bloodwork comparison for preventive healthcare.</h1><p className="text-ink/65 text-lg leading-relaxed max-w-2xl">Compare blood tests by biomarkers, lab quality, hidden charges, fasting needs, doctor interpretation, and family suitability before booking.</p><div className="flex flex-wrap gap-3 mt-6"><Button variant="primary" icon="search" onClick={() => document.getElementById("raktasetu-search")?.focus()}>Find a test</Button><Button variant="outline" icon="fileText" onClick={() => alert("Mock report upload: no file leaves your browser in this prototype.")}>Upload report</Button></div></div>
        <div className="grid grid-cols-2 gap-4">{([["Tests reviewed", RAKTASETU_TESTS.length], ["NABL labs", RAKTASETU_TESTS.filter(t => t.nabl).length], ["Home collection", RAKTASETU_TESTS.filter(t => t.home).length], ["Doctor review", RAKTASETU_TESTS.filter(t => t.doctor).length]] as Array<[string, number]>).map(([label, value]) => <div key={label} className="bg-white rounded-2xl p-5 border border-ink/5 shadow-glass"><p className="text-xs uppercase tracking-widest text-ink/40 font-medium">{label}</p><p className="serif text-3xl text-ink mt-2">{value}</p></div>)}</div>
      </div>
      <div className="bg-white rounded-3xl border border-ink/5 shadow-glass p-4 sm:p-5 mb-8"><div className="flex flex-col lg:flex-row gap-3"><div className="flex-1 relative"><Icon name="search" size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-ink/35" /><input id="raktasetu-search" value={query} onChange={e => setQuery(e.target.value)} className="w-full pl-11 pr-4 py-3 rounded-xl border border-ink/10 focus:border-aqua-deep focus:ring-2 focus:ring-aqua/20 outline-none" placeholder="Search CBC, thyroid, diabetes, biomarkers, labs..." /></div><div className="flex flex-wrap gap-2">{cats.map(c => <button key={c.id} onClick={() => setCategory(c.id)} className={(category === c.id ? "bg-ink text-cream" : "bg-cream-warm text-ink/70 hover:bg-aqua-light") + " px-3 py-2 rounded-xl text-sm font-medium transition-colors"}>{c.label}</button>)}</div></div></div>
      <div className="grid lg:grid-cols-[280px_1fr] gap-6">
        <aside className="space-y-4"><Card hover={false}><h3 className="font-semibold text-ink mb-3">Quality checks</h3>{["NABL accreditation", "Hidden charges", "Home collection", "Fasting needed", "Doctor interpretation", "Missing biomarkers"].map(item => <div key={item} className="flex items-center gap-2 text-sm text-ink/65 mb-2"><Icon name="check" size={14} className="text-aqua-deep" />{item}</div>)}</Card><Card hover={false} className="bg-cream-warm"><h3 className="font-semibold text-ink mb-2">Report upload preview</h3><p className="text-sm text-ink/60 mb-4">Designed to flag out-of-range values, missing follow-up markers, and questions to ask your doctor.</p><Button variant="outline" fullWidth icon="fileText" onClick={() => alert("Mock upload flow would parse a blood report.")}>Upload report</Button></Card></aside>
        <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-5">{filtered.map(t => <Card key={t.id} hover={false} className="flex flex-col"><div className="flex items-start justify-between gap-3 mb-3"><div><p className="text-[10px] uppercase tracking-widest text-ink/40 font-medium">{t.lab}</p><h3 className="font-semibold text-ink leading-snug mt-1">{t.name}</h3></div><Badge color={t.color}>{t.verdict}</Badge></div><div className="flex flex-wrap gap-1 mb-3">{t.badges.map(b => <span key={b} className="text-[10px] uppercase tracking-wide bg-aqua-light text-aqua-deep px-2 py-0.5 rounded-full">{b}</span>)}</div><div className="flex items-end justify-between mb-3"><div><p className="serif text-2xl font-semibold text-ink">Rs {t.price}</p><p className="text-xs text-ink/35 line-through">Rs {t.origPrice}</p></div><p className="text-xs text-ink/50">{t.turnaround}h · {t.fasting ? "Fasting" : "No fasting"}</p></div><p className="text-sm text-ink/65 leading-relaxed mb-4">{t.summary}</p><div className="flex flex-wrap gap-1 mb-4">{t.biomarkers.slice(0, 5).map(b => <span key={b} className="text-[11px] bg-cream-warm text-ink/65 px-2 py-1 rounded-lg">{b}</span>)}{t.biomarkers.length > 5 && <span className="text-[11px] bg-cream-warm text-ink/65 px-2 py-1 rounded-lg">+{t.biomarkers.length - 5}</span>}</div><div className="mt-auto flex gap-2"><Button variant="outline" size="sm" className="flex-1" onClick={() => setSelected(t)}>Details</Button><button onClick={() => toggleCompare(t.id)} className={(compare.includes(t.id) ? "bg-ink text-cream" : "bg-cream-warm text-ink/70 hover:bg-aqua-light") + " px-3 py-2 rounded-full text-sm font-medium transition-colors"}>{compare.includes(t.id) ? "Added" : "Compare"}</button></div></Card>)}</div>
      </div>
      {compare.length > 0 && <div className="fixed bottom-0 left-0 right-0 z-30 bg-white border-t border-ink/10 p-4 shadow-lift"><div className="max-w-7xl mx-auto flex flex-col md:flex-row md:items-center justify-between gap-3"><p className="text-sm font-medium text-ink">{compare.length} blood test{compare.length > 1 ? "s" : ""} selected</p><div className="flex gap-2"><Button variant="ghost" size="sm" onClick={() => setCompare([])}>Clear</Button><Button variant="primary" size="sm" onClick={() => setSelected("compare")}>Compare biomarkers</Button></div></div></div>}
      <Modal isOpen={!!selected} onClose={() => setSelected(null)} title={selected === "compare" ? "Bloodwork Comparison" : selected?.name} size={selected === "compare" ? "xl" : "lg"}>
        {selected === "compare" ? <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-ink/10"><th className="text-left py-3 pr-3">Feature</th>{compareTests.map(t => <th key={t.id} className="text-left py-3 px-3 min-w-[180px]">{t.name}</th>)}</tr></thead><tbody>{([["Lab", t => t.lab], ["Total price", t => "Rs " + (t.price + t.hidden)], ["NABL", t => t.nabl ? "Yes" : "No"], ["Fasting", t => t.fasting ? "Yes" : "No"], ["Doctor review", t => t.doctor ? "Yes" : "No"], ["Missing", t => t.missing.length ? t.missing.join(", ") : "None"]] as Array<[string, (t: any) => React.ReactNode]>).map(row => <tr key={row[0]} className="border-b border-ink/5"><td className="py-3 pr-3 font-medium text-ink/70">{row[0]}</td>{compareTests.map(t => <td key={t.id} className="py-3 px-3 text-ink/65">{row[1](t)}</td>)}</tr>)}</tbody></table></div> : selected && <div className="space-y-5"><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-ink/50">{selected.lab} · {selected.rating} star · {selected.reviews.toLocaleString()} reviews</p><p className="text-2xl font-semibold text-ink mt-2">Rs {selected.price} <span className="text-sm text-ink/40 line-through">Rs {selected.origPrice}</span></p></div><Badge color={selected.color}>{selected.verdict}</Badge></div><p className="text-sm text-ink/70 leading-relaxed">{selected.summary}</p><div className="grid sm:grid-cols-2 gap-3"><div className="bg-cream-warm rounded-xl p-4"><h4 className="font-semibold text-ink mb-2">Best for</h4><p className="text-sm text-ink/65">{selected.use}</p></div><div className="bg-cream-warm rounded-xl p-4"><h4 className="font-semibold text-ink mb-2">Caution</h4><p className="text-sm text-ink/65">{selected.caution}</p></div></div><div><h4 className="font-semibold text-ink mb-2">Included biomarkers</h4><div className="flex flex-wrap gap-2">{selected.biomarkers.map(b => <span key={b} className="px-3 py-2 bg-aqua-light text-aqua-deep rounded-lg text-sm">{b}</span>)}</div></div>{selected.missing.length > 0 && <div><h4 className="font-semibold text-ink mb-2">Missing or add-on markers</h4><div className="flex flex-wrap gap-2">{selected.missing.map(b => <span key={b} className="px-3 py-2 bg-terracotta-soft text-terracotta-deep rounded-lg text-sm">{b}</span>)}</div></div>}<Disclaimer type="general" /><Button variant="primary" fullWidth onClick={() => alert("Mock booking flow would open lab options.")}>Book Test</Button></div>}
      </Modal>
    </div>
  );
};


