-- Product image import chunk 9 of 9
-- Run chunks in numbered order.

insert into product_tags (product_id, label, tag_type)
select p.id, v.label, v.tag_type from (values
  ('IMG-device-accu-chek-accu-chek-guide-blood-glucose-monitoring-system', 'Glucometer', 'workbook'),
  ('IMG-device-accu-chek-accu-chek-guide-blood-glucose-monitoring-system', 'Device kit', 'workbook'),
  ('IMG-device-accu-chek-accu-chek-guide-blood-glucose-monitoring-system', 'Direct Image', 'workbook'),
  ('IMG-device-accu-chek-accu-chek-guide-blood-glucose-monitoring-system', 'Source Verified', 'workbook'),
  ('IMG-device-accu-chek-accu-chek-instant-blood-glucose-meter', 'Glucometer', 'workbook'),
  ('IMG-device-accu-chek-accu-chek-instant-blood-glucose-meter', 'Device kit', 'workbook'),
  ('IMG-device-accu-chek-accu-chek-instant-blood-glucose-meter', 'Direct Image', 'workbook'),
  ('IMG-device-accu-chek-accu-chek-instant-blood-glucose-meter', 'Manual Check', 'workbook'),
  ('IMG-device-accu-chek-accu-chek-instant-s-blood-glucose-meter', 'Glucometer', 'workbook'),
  ('IMG-device-accu-chek-accu-chek-instant-s-blood-glucose-meter', 'Device kit', 'workbook'),
  ('IMG-device-accu-chek-accu-chek-instant-s-blood-glucose-meter', 'Direct Image', 'workbook'),
  ('IMG-device-accu-chek-accu-chek-instant-s-blood-glucose-meter', 'Manual Check', 'workbook'),
  ('IMG-device-accu-chek-accu-chek-active-blood-glucose-meter', 'Glucometer', 'workbook'),
  ('IMG-device-accu-chek-accu-chek-active-blood-glucose-meter', 'Device kit', 'workbook'),
  ('IMG-device-accu-chek-accu-chek-active-blood-glucose-meter', 'Direct Image', 'workbook'),
  ('IMG-device-accu-chek-accu-chek-active-blood-glucose-meter', 'Source Verified', 'workbook'),
  ('IMG-device-accu-chek-accu-chek-guide-test-strips', 'Test strips', 'workbook'),
  ('IMG-device-accu-chek-accu-chek-guide-test-strips', 'Strips', 'workbook'),
  ('IMG-device-accu-chek-accu-chek-guide-test-strips', 'Image Needs Review', 'workbook'),
  ('IMG-device-accu-chek-accu-chek-guide-test-strips', 'Manual Check', 'workbook'),
  ('IMG-device-accu-chek-accu-chek-active-test-strips', 'Test strips', 'workbook'),
  ('IMG-device-accu-chek-accu-chek-active-test-strips', 'Strips', 'workbook'),
  ('IMG-device-accu-chek-accu-chek-active-test-strips', 'Image Needs Review', 'workbook'),
  ('IMG-device-accu-chek-accu-chek-active-test-strips', 'Source Verified', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-blood-glucose-monitor-bg-03', 'Glucometer', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-blood-glucose-monitor-bg-03', 'Device kit', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-blood-glucose-monitor-bg-03', 'Image Needs Review', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-blood-glucose-monitor-bg-03', 'Manual Check', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-blood-glucose-monitor-bg-03-test-strips', 'Test strips', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-blood-glucose-monitor-bg-03-test-strips', 'Strips', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-blood-glucose-monitor-bg-03-test-strips', 'Image Needs Review', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-blood-glucose-monitor-bg-03-test-strips', 'Manual Check', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-bp-02-blood-pressure-monitor', 'Blood pressure monitor', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-bp-02-blood-pressure-monitor', 'Upper arm monitor', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-bp-02-blood-pressure-monitor', 'Image Needs Review', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-bp-02-blood-pressure-monitor', 'Source Verified', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-bp-09-blood-pressure-monitor', 'Blood pressure monitor', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-bp-09-blood-pressure-monitor', 'Upper arm monitor', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-bp-09-blood-pressure-monitor', 'Image Needs Review', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-bp-09-blood-pressure-monitor', 'Source Verified', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-bp-14-blood-pressure-monitor', 'Blood pressure monitor', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-bp-14-blood-pressure-monitor', 'Upper arm monitor', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-bp-14-blood-pressure-monitor', 'Image Needs Review', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-bp-14-blood-pressure-monitor', 'Source Verified', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-bp-15-blood-pressure-monitor', 'Blood pressure monitor', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-bp-15-blood-pressure-monitor', 'Upper arm monitor', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-bp-15-blood-pressure-monitor', 'Image Needs Review', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-bp-15-blood-pressure-monitor', 'Source Verified', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-digital-thermometer', 'Thermometer', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-digital-thermometer', 'Digital thermometer', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-digital-thermometer', 'Image Needs Review', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-digital-thermometer', 'Manual Check', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-digital-weighing-scale', 'Weighing scale', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-digital-weighing-scale', 'Digital scale', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-digital-weighing-scale', 'Image Needs Review', 'workbook'),
  ('IMG-device-dr-morepen-dr-morepen-digital-weighing-scale', 'Manual Check', 'workbook'),
  ('IMG-device-omron-omron-hem-7120-blood-pressure-monitor', 'Blood pressure monitor', 'workbook'),
  ('IMG-device-omron-omron-hem-7120-blood-pressure-monitor', 'Upper arm monitor', 'workbook'),
  ('IMG-device-omron-omron-hem-7120-blood-pressure-monitor', 'Image Needs Review', 'workbook'),
  ('IMG-device-omron-omron-hem-7120-blood-pressure-monitor', 'Manual Check', 'workbook'),
  ('IMG-device-omron-omron-hem-7156-blood-pressure-monitor', 'Blood pressure monitor', 'workbook'),
  ('IMG-device-omron-omron-hem-7156-blood-pressure-monitor', 'Upper arm monitor', 'workbook'),
  ('IMG-device-omron-omron-hem-7156-blood-pressure-monitor', 'Image Needs Review', 'workbook'),
  ('IMG-device-omron-omron-hem-7156-blood-pressure-monitor', 'Manual Check', 'workbook'),
  ('IMG-device-omron-omron-hem-7361t-blood-pressure-monitor', 'Blood pressure monitor', 'workbook'),
  ('IMG-device-omron-omron-hem-7361t-blood-pressure-monitor', 'Upper arm monitor', 'workbook'),
  ('IMG-device-omron-omron-hem-7361t-blood-pressure-monitor', 'Image Needs Review', 'workbook'),
  ('IMG-device-omron-omron-hem-7361t-blood-pressure-monitor', 'Manual Check', 'workbook'),
  ('IMG-device-omron-omron-digital-thermometer', 'Thermometer', 'workbook'),
  ('IMG-device-omron-omron-digital-thermometer', 'Digital thermometer', 'workbook'),
  ('IMG-device-omron-omron-digital-thermometer', 'Image Needs Review', 'workbook'),
  ('IMG-device-omron-omron-digital-thermometer', 'Manual Check', 'workbook'),
  ('IMG-device-omron-omron-body-composition-monitor', 'Body composition monitor', 'workbook'),
  ('IMG-device-omron-omron-body-composition-monitor', 'Digital monitor', 'workbook'),
  ('IMG-device-omron-omron-body-composition-monitor', 'Image Needs Review', 'workbook'),
  ('IMG-device-omron-omron-body-composition-monitor', 'Manual Check', 'workbook'),
  ('IMG-device-philips-avent-philips-avent-bottle-warmer', 'Baby feeding device', 'workbook'),
  ('IMG-device-philips-avent-philips-avent-bottle-warmer', 'Electric warmer', 'workbook'),
  ('IMG-device-philips-avent-philips-avent-bottle-warmer', 'Image Needs Review', 'workbook'),
  ('IMG-device-philips-avent-philips-avent-bottle-warmer', 'Manual Check', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-multivitamin', 'Multivitamin', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-multivitamin', 'Tablet', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-multivitamin', 'Image Needs Review', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-multivitamin', 'Manual Check', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-fish-oil-1000mg', 'Omega-3 supplement', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-fish-oil-1000mg', 'Capsules', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-fish-oil-1000mg', 'Image Needs Review', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-fish-oil-1000mg', 'Manual Check', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-vitamin-d3', 'Vitamin supplement', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-vitamin-d3', 'Tablets', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-vitamin-d3', 'Image Needs Review', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-vitamin-d3', 'Manual Check', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-calcium-vitamin-d3', 'Mineral supplement', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-calcium-vitamin-d3', 'Tablets', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-calcium-vitamin-d3', 'Image Needs Review', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-calcium-vitamin-d3', 'Manual Check', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-magnesium-glycinate', 'Mineral supplement', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-magnesium-glycinate', 'Tablets', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-magnesium-glycinate', 'Image Needs Review', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-magnesium-glycinate', 'Manual Check', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-biotin', 'Vitamin supplement', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-biotin', 'Tablets', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-biotin', 'Image Needs Review', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-biotin', 'Manual Check', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-glutathione-effervescent-orange', 'Antioxidant supplement', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-glutathione-effervescent-orange', 'Effervescent tablets', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-glutathione-effervescent-orange', 'Image Needs Review', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-glutathione-effervescent-orange', 'Manual Check', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-pre-and-probiotics', 'Gut supplement', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-pre-and-probiotics', 'Capsules', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-pre-and-probiotics', 'Image Needs Review', 'workbook'),
  ('IMG-supplement-healthkart-hk-vitals-hk-vitals-pre-and-probiotics', 'Manual Check', 'workbook'),
  ('IMG-supplement-healthaid-healthaid-children-s-multivitamin-gummies-with-omega-3', 'Children supplement', 'workbook'),
  ('IMG-supplement-healthaid-healthaid-children-s-multivitamin-gummies-with-omega-3', 'Gummies', 'workbook'),
  ('IMG-supplement-healthaid-healthaid-children-s-multivitamin-gummies-with-omega-3', 'Image Needs Review', 'workbook'),
  ('IMG-supplement-healthaid-healthaid-children-s-multivitamin-gummies-with-omega-3', 'Manual Check', 'workbook'),
  ('IMG-supplement-wellbeing-nutrition-wellbeing-nutrition-vegan-pro-collagen', 'Collagen booster', 'workbook'),
  ('IMG-supplement-wellbeing-nutrition-wellbeing-nutrition-vegan-pro-collagen', 'Powder', 'workbook'),
  ('IMG-supplement-wellbeing-nutrition-wellbeing-nutrition-vegan-pro-collagen', 'Image Needs Review', 'workbook'),
  ('IMG-supplement-wellbeing-nutrition-wellbeing-nutrition-vegan-pro-collagen', 'Manual Check', 'workbook'),
  ('IMG-supplement-wellbeing-nutrition-wellbeing-nutrition-melts-multivitamin', 'Multivitamin', 'workbook'),
  ('IMG-supplement-wellbeing-nutrition-wellbeing-nutrition-melts-multivitamin', 'Oral strips', 'workbook'),
  ('IMG-supplement-wellbeing-nutrition-wellbeing-nutrition-melts-multivitamin', 'Image Needs Review', 'workbook'),
  ('IMG-supplement-wellbeing-nutrition-wellbeing-nutrition-melts-multivitamin', 'Manual Check', 'workbook'),
  ('IMG-supplement-wellbeing-nutrition-wellbeing-nutrition-apple-cider-vinegar-effervescent', 'ACV supplement', 'workbook'),
  ('IMG-supplement-wellbeing-nutrition-wellbeing-nutrition-apple-cider-vinegar-effervescent', 'Effervescent tablets', 'workbook'),
  ('IMG-supplement-wellbeing-nutrition-wellbeing-nutrition-apple-cider-vinegar-effervescent', 'Image Needs Review', 'workbook'),
  ('IMG-supplement-wellbeing-nutrition-wellbeing-nutrition-apple-cider-vinegar-effervescent', 'Manual Check', 'workbook'),
  ('IMG-supplement-plix-plix-glowy-skin-effervescent', 'Beauty supplement', 'workbook'),
  ('IMG-supplement-plix-plix-glowy-skin-effervescent', 'Effervescent tablets', 'workbook'),
  ('IMG-supplement-plix-plix-glowy-skin-effervescent', 'Image Needs Review', 'workbook'),
  ('IMG-supplement-plix-plix-glowy-skin-effervescent', 'Manual Check', 'workbook'),
  ('IMG-supplement-plix-plix-collagen-booster', 'Collagen booster', 'workbook'),
  ('IMG-supplement-plix-plix-collagen-booster', 'Powder/Jar', 'workbook'),
  ('IMG-supplement-plix-plix-collagen-booster', 'Image Needs Review', 'workbook'),
  ('IMG-supplement-plix-plix-collagen-booster', 'Manual Check', 'workbook'),
  ('IMG-supplement-plix-plix-daily-greens', 'Greens supplement', 'workbook'),
  ('IMG-supplement-plix-plix-daily-greens', 'Powder', 'workbook'),
  ('IMG-supplement-plix-plix-daily-greens', 'Image Needs Review', 'workbook'),
  ('IMG-supplement-plix-plix-daily-greens', 'Manual Check', 'workbook'),
  ('IMG-supplement-organic-india-organic-india-ashwagandha-capsules', 'Herbal supplement', 'workbook'),
  ('IMG-supplement-organic-india-organic-india-ashwagandha-capsules', 'Capsules', 'workbook'),
  ('IMG-supplement-organic-india-organic-india-ashwagandha-capsules', 'Image Needs Review', 'workbook'),
  ('IMG-supplement-organic-india-organic-india-ashwagandha-capsules', 'Manual Check', 'workbook'),
  ('IMG-supplement-organic-india-organic-india-flaxseed-oil-capsules', 'Omega supplement', 'workbook'),
  ('IMG-supplement-organic-india-organic-india-flaxseed-oil-capsules', 'Capsules', 'workbook'),
  ('IMG-supplement-organic-india-organic-india-flaxseed-oil-capsules', 'Image Needs Review', 'workbook'),
  ('IMG-supplement-organic-india-organic-india-flaxseed-oil-capsules', 'Manual Check', 'workbook'),
  ('IMG-supplement-fast-up-fast-up-apple-cider-vinegar-effervescent', 'ACV supplement', 'workbook'),
  ('IMG-supplement-fast-up-fast-up-apple-cider-vinegar-effervescent', 'Effervescent tablets', 'workbook'),
  ('IMG-supplement-fast-up-fast-up-apple-cider-vinegar-effervescent', 'Image Needs Review', 'workbook'),
  ('IMG-supplement-fast-up-fast-up-apple-cider-vinegar-effervescent', 'Manual Check', 'workbook'),
  ('IMG-supplement-fast-up-fast-up-activate-multivitamin', 'Multivitamin', 'workbook'),
  ('IMG-supplement-fast-up-fast-up-activate-multivitamin', 'Effervescent tablets', 'workbook'),
  ('IMG-supplement-fast-up-fast-up-activate-multivitamin', 'Image Needs Review', 'workbook'),
  ('IMG-supplement-fast-up-fast-up-activate-multivitamin', 'Manual Check', 'workbook'),
  ('IMG-supplement-truebasics-truebasics-ultra-omega-3', 'Omega-3 supplement', 'workbook'),
  ('IMG-supplement-truebasics-truebasics-ultra-omega-3', 'Softgels', 'workbook'),
  ('IMG-supplement-truebasics-truebasics-ultra-omega-3', 'Image Needs Review', 'workbook'),
  ('IMG-supplement-truebasics-truebasics-ultra-omega-3', 'Manual Check', 'workbook'),
  ('IMG-ayurveda-himalaya-himalaya-liv-52-tablet', 'Ayurvedic formulation', 'workbook'),
  ('IMG-ayurveda-himalaya-himalaya-liv-52-tablet', 'Tablet', 'workbook'),
  ('IMG-ayurveda-himalaya-himalaya-liv-52-tablet', 'Image Needs Review', 'workbook'),
  ('IMG-ayurveda-himalaya-himalaya-liv-52-tablet', 'Manual Check', 'workbook'),
  ('IMG-ayurveda-himalaya-himalaya-liv-52-ds-tablet', 'Ayurvedic formulation', 'workbook'),
  ('IMG-ayurveda-himalaya-himalaya-liv-52-ds-tablet', 'Tablet', 'workbook'),
  ('IMG-ayurveda-himalaya-himalaya-liv-52-ds-tablet', 'Image Needs Review', 'workbook'),
  ('IMG-ayurveda-himalaya-himalaya-liv-52-ds-tablet', 'Manual Check', 'workbook'),
  ('IMG-ayurveda-himalaya-himalaya-liv-52-syrup', 'Ayurvedic formulation', 'workbook'),
  ('IMG-ayurveda-himalaya-himalaya-liv-52-syrup', 'Syrup', 'workbook'),
  ('IMG-ayurveda-himalaya-himalaya-liv-52-syrup', 'Image Needs Review', 'workbook'),
  ('IMG-ayurveda-himalaya-himalaya-liv-52-syrup', 'Manual Check', 'workbook'),
  ('IMG-ayurveda-himalaya-himalaya-organic-ashwagandha', 'Ayurvedic supplement', 'workbook'),
  ('IMG-ayurveda-himalaya-himalaya-organic-ashwagandha', 'Capsules/Tablets', 'workbook'),
  ('IMG-ayurveda-himalaya-himalaya-organic-ashwagandha', 'Image Needs Review', 'workbook'),
  ('IMG-ayurveda-himalaya-himalaya-organic-ashwagandha', 'Manual Check', 'workbook'),
  ('IMG-ayurveda-himalaya-himalaya-shilajit-capsules', 'Ayurvedic supplement', 'workbook'),
  ('IMG-ayurveda-himalaya-himalaya-shilajit-capsules', 'Capsules', 'workbook'),
  ('IMG-ayurveda-himalaya-himalaya-shilajit-capsules', 'Image Needs Review', 'workbook'),
  ('IMG-ayurveda-himalaya-himalaya-shilajit-capsules', 'Manual Check', 'workbook'),
  ('IMG-ayurveda-himalaya-himalaya-tentex-royal-capsules', 'Ayurvedic supplement', 'workbook'),
  ('IMG-ayurveda-himalaya-himalaya-tentex-royal-capsules', 'Capsules', 'workbook'),
  ('IMG-ayurveda-himalaya-himalaya-tentex-royal-capsules', 'Image Needs Review', 'workbook'),
  ('IMG-ayurveda-himalaya-himalaya-tentex-royal-capsules', 'Manual Check', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-chyawanprash-awaleha', 'Ayurvedic health food', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-chyawanprash-awaleha', 'Awaleha', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-chyawanprash-awaleha', 'Image Needs Review', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-chyawanprash-awaleha', 'Manual Check', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-chyawanprakash-sugarfree', 'Ayurvedic health food', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-chyawanprakash-sugarfree', 'Awaleha', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-chyawanprakash-sugarfree', 'Image Needs Review', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-chyawanprakash-sugarfree', 'Manual Check', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-kesarprash', 'Ayurvedic health food', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-kesarprash', 'Awaleha', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-kesarprash', 'Image Needs Review', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-kesarprash', 'Manual Check', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-pudin-hara-pearls', 'Ayurvedic digestive', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-pudin-hara-pearls', 'Pearls', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-pudin-hara-pearls', 'Image Needs Review', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-pudin-hara-pearls', 'Manual Check', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-sat-isabgol', 'Ayurvedic fibre', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-sat-isabgol', 'Powder', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-sat-isabgol', 'Image Needs Review', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-sat-isabgol', 'Manual Check', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-honitus-syrup', 'Ayurvedic cough product', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-honitus-syrup', 'Syrup', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-honitus-syrup', 'Image Needs Review', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-honitus-syrup', 'Manual Check', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-giloy-juice', 'Ayurvedic juice', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-giloy-juice', 'Juice', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-giloy-juice', 'Image Needs Review', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-giloy-juice', 'Manual Check', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-amla-juice', 'Ayurvedic juice', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-amla-juice', 'Juice', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-amla-juice', 'Image Needs Review', 'workbook'),
  ('IMG-ayurveda-dabur-dabur-amla-juice', 'Manual Check', 'workbook'),
  ('IMG-ayurveda-kapiva-kapiva-liver-care-juice', 'Ayurvedic juice', 'workbook'),
  ('IMG-ayurveda-kapiva-kapiva-liver-care-juice', 'Juice', 'workbook'),
  ('IMG-ayurveda-kapiva-kapiva-liver-care-juice', 'Image Needs Review', 'workbook'),
  ('IMG-ayurveda-kapiva-kapiva-liver-care-juice', 'Manual Check', 'workbook'),
  ('IMG-ayurveda-kapiva-kapiva-triphala-juice', 'Ayurvedic juice', 'workbook'),
  ('IMG-ayurveda-kapiva-kapiva-triphala-juice', 'Juice', 'workbook'),
  ('IMG-ayurveda-kapiva-kapiva-triphala-juice', 'Image Needs Review', 'workbook'),
  ('IMG-ayurveda-kapiva-kapiva-triphala-juice', 'Manual Check', 'workbook'),
  ('IMG-ayurveda-kapiva-kapiva-aloe-vera-juice', 'Ayurvedic juice', 'workbook'),
  ('IMG-ayurveda-kapiva-kapiva-aloe-vera-juice', 'Juice', 'workbook'),
  ('IMG-ayurveda-kapiva-kapiva-aloe-vera-juice', 'Image Needs Review', 'workbook'),
  ('IMG-ayurveda-kapiva-kapiva-aloe-vera-juice', 'Manual Check', 'workbook'),
  ('IMG-ayurveda-kapiva-kapiva-bp-care-juice', 'Ayurvedic juice', 'workbook'),
  ('IMG-ayurveda-kapiva-kapiva-bp-care-juice', 'Juice', 'workbook'),
  ('IMG-ayurveda-kapiva-kapiva-bp-care-juice', 'Image Needs Review', 'workbook'),
  ('IMG-ayurveda-kapiva-kapiva-bp-care-juice', 'Manual Check', 'workbook'),
  ('IMG-ayurveda-kapiva-kapiva-cholest-fit-juice', 'Ayurvedic juice', 'workbook'),
  ('IMG-ayurveda-kapiva-kapiva-cholest-fit-juice', 'Juice', 'workbook'),
  ('IMG-ayurveda-kapiva-kapiva-cholest-fit-juice', 'Image Needs Review', 'workbook'),
  ('IMG-ayurveda-kapiva-kapiva-cholest-fit-juice', 'Manual Check', 'workbook'),
  ('IMG-ayurveda-organic-india-organic-india-arjuna-capsules', 'Ayurvedic capsule', 'workbook'),
  ('IMG-ayurveda-organic-india-organic-india-arjuna-capsules', 'Capsules', 'workbook'),
  ('IMG-ayurveda-organic-india-organic-india-arjuna-capsules', 'Image Needs Review', 'workbook'),
  ('IMG-ayurveda-organic-india-organic-india-arjuna-capsules', 'Manual Check', 'workbook'),
  ('IMG-personal-care-himalaya-himalaya-purifying-neem-face-wash', 'Face wash', 'workbook'),
  ('IMG-personal-care-himalaya-himalaya-purifying-neem-face-wash', 'Face wash', 'workbook'),
  ('IMG-personal-care-himalaya-himalaya-purifying-neem-face-wash', 'Image Needs Review', 'workbook'),
  ('IMG-personal-care-himalaya-himalaya-purifying-neem-face-wash', 'Manual Check', 'workbook'),
  ('IMG-personal-care-himalaya-himalaya-anti-hair-fall-bhringaraja-shampoo', 'Shampoo', 'workbook'),
  ('IMG-personal-care-himalaya-himalaya-anti-hair-fall-bhringaraja-shampoo', 'Shampoo', 'workbook'),
  ('IMG-personal-care-himalaya-himalaya-anti-hair-fall-bhringaraja-shampoo', 'Image Needs Review', 'workbook'),
  ('IMG-personal-care-himalaya-himalaya-anti-hair-fall-bhringaraja-shampoo', 'Manual Check', 'workbook'),
  ('IMG-personal-care-dabur-dabur-red-toothpaste', 'Toothpaste', 'workbook'),
  ('IMG-personal-care-dabur-dabur-red-toothpaste', 'Toothpaste', 'workbook'),
  ('IMG-personal-care-dabur-dabur-red-toothpaste', 'Image Needs Review', 'workbook'),
  ('IMG-personal-care-dabur-dabur-red-toothpaste', 'Manual Check', 'workbook'),
  ('IMG-personal-care-dabur-dabur-red-gel-toothpaste', 'Toothpaste', 'workbook'),
  ('IMG-personal-care-dabur-dabur-red-gel-toothpaste', 'Toothpaste gel', 'workbook'),
  ('IMG-personal-care-dabur-dabur-red-gel-toothpaste', 'Image Needs Review', 'workbook'),
  ('IMG-personal-care-dabur-dabur-red-gel-toothpaste', 'Manual Check', 'workbook'),
  ('IMG-personal-care-dabur-dabur-vatika-hair-oil', 'Hair oil', 'workbook'),
  ('IMG-personal-care-dabur-dabur-vatika-hair-oil', 'Oil', 'workbook'),
  ('IMG-personal-care-dabur-dabur-vatika-hair-oil', 'Image Needs Review', 'workbook'),
  ('IMG-personal-care-dabur-dabur-vatika-hair-oil', 'Manual Check', 'workbook'),
  ('IMG-personal-care-dabur-dabur-vatika-shampoo', 'Shampoo', 'workbook'),
  ('IMG-personal-care-dabur-dabur-vatika-shampoo', 'Shampoo', 'workbook'),
  ('IMG-personal-care-dabur-dabur-vatika-shampoo', 'Image Needs Review', 'workbook'),
  ('IMG-personal-care-dabur-dabur-vatika-shampoo', 'Manual Check', 'workbook'),
  ('IMG-personal-care-dabur-dabur-gulabari-rose-water', 'Skin toner', 'workbook'),
  ('IMG-personal-care-dabur-dabur-gulabari-rose-water', 'Liquid', 'workbook'),
  ('IMG-personal-care-dabur-dabur-gulabari-rose-water', 'Image Needs Review', 'workbook'),
  ('IMG-personal-care-dabur-dabur-gulabari-rose-water', 'Manual Check', 'workbook'),
  ('IMG-personal-care-dabur-dabur-odomos-naturals-cream', 'Mosquito repellent', 'workbook'),
  ('IMG-personal-care-dabur-dabur-odomos-naturals-cream', 'Cream', 'workbook'),
  ('IMG-personal-care-dabur-dabur-odomos-naturals-cream', 'Image Needs Review', 'workbook'),
  ('IMG-personal-care-dabur-dabur-odomos-naturals-cream', 'Manual Check', 'workbook'),
  ('IMG-personal-care-mamaearth-mamaearth-ubtan-face-wash', 'Face wash', 'workbook'),
  ('IMG-personal-care-mamaearth-mamaearth-ubtan-face-wash', 'Face wash', 'workbook'),
  ('IMG-personal-care-mamaearth-mamaearth-ubtan-face-wash', 'Image Needs Review', 'workbook'),
  ('IMG-personal-care-mamaearth-mamaearth-ubtan-face-wash', 'Manual Check', 'workbook'),
  ('IMG-personal-care-mamaearth-mamaearth-vitamin-c-face-wash', 'Face wash', 'workbook'),
  ('IMG-personal-care-mamaearth-mamaearth-vitamin-c-face-wash', 'Face wash', 'workbook'),
  ('IMG-personal-care-mamaearth-mamaearth-vitamin-c-face-wash', 'Image Needs Review', 'workbook'),
  ('IMG-personal-care-mamaearth-mamaearth-vitamin-c-face-wash', 'Manual Check', 'workbook'),
  ('IMG-personal-care-mamaearth-mamaearth-onion-shampoo', 'Shampoo', 'workbook'),
  ('IMG-personal-care-mamaearth-mamaearth-onion-shampoo', 'Shampoo', 'workbook'),
  ('IMG-personal-care-mamaearth-mamaearth-onion-shampoo', 'Image Needs Review', 'workbook'),
  ('IMG-personal-care-mamaearth-mamaearth-onion-shampoo', 'Manual Check', 'workbook'),
  ('IMG-personal-care-mamaearth-mamaearth-tea-tree-face-wash', 'Face wash', 'workbook'),
  ('IMG-personal-care-mamaearth-mamaearth-tea-tree-face-wash', 'Face wash', 'workbook'),
  ('IMG-personal-care-mamaearth-mamaearth-tea-tree-face-wash', 'Image Needs Review', 'workbook'),
  ('IMG-personal-care-mamaearth-mamaearth-tea-tree-face-wash', 'Manual Check', 'workbook'),
  ('IMG-personal-care-philips-philips-oneblade-trimmer', 'Grooming device', 'workbook'),
  ('IMG-personal-care-philips-philips-oneblade-trimmer', 'Trimmer', 'workbook'),
  ('IMG-personal-care-philips-philips-oneblade-trimmer', 'Image Needs Review', 'workbook'),
  ('IMG-personal-care-philips-philips-oneblade-trimmer', 'Manual Check', 'workbook'),
  ('IMG-personal-care-philips-philips-hair-dryer', 'Hair styling device', 'workbook'),
  ('IMG-personal-care-philips-philips-hair-dryer', 'Hair dryer', 'workbook'),
  ('IMG-personal-care-philips-philips-hair-dryer', 'Image Needs Review', 'workbook'),
  ('IMG-personal-care-philips-philips-hair-dryer', 'Manual Check', 'workbook'),
  ('IMG-personal-care-philips-philips-beard-trimmer', 'Grooming device', 'workbook'),
  ('IMG-personal-care-philips-philips-beard-trimmer', 'Trimmer', 'workbook'),
  ('IMG-personal-care-philips-philips-beard-trimmer', 'Image Needs Review', 'workbook'),
  ('IMG-personal-care-philips-philips-beard-trimmer', 'Manual Check', 'workbook'),
  ('IMG-personal-care-philips-philips-electric-shaver', 'Grooming device', 'workbook'),
  ('IMG-personal-care-philips-philips-electric-shaver', 'Shaver', 'workbook'),
  ('IMG-personal-care-philips-philips-electric-shaver', 'Image Needs Review', 'workbook'),
  ('IMG-personal-care-philips-philips-electric-shaver', 'Manual Check', 'workbook'),
  ('IMG-personal-care-philips-philips-hair-straightener', 'Hair styling device', 'workbook'),
  ('IMG-personal-care-philips-philips-hair-straightener', 'Straightener', 'workbook'),
  ('IMG-personal-care-philips-philips-hair-straightener', 'Image Needs Review', 'workbook'),
  ('IMG-personal-care-philips-philips-hair-straightener', 'Manual Check', 'workbook'),
  ('IMG-personal-care-philips-philips-epilator', 'Hair removal device', 'workbook'),
  ('IMG-personal-care-philips-philips-epilator', 'Epilator', 'workbook'),
  ('IMG-personal-care-philips-philips-epilator', 'Image Needs Review', 'workbook'),
  ('IMG-personal-care-philips-philips-epilator', 'Manual Check', 'workbook'),
  ('IMG-personal-care-dabur-nuface-nuface-ultra-sunscreen-spf-60', 'Sunscreen', 'workbook'),
  ('IMG-personal-care-dabur-nuface-nuface-ultra-sunscreen-spf-60', 'Cream', 'workbook'),
  ('IMG-personal-care-dabur-nuface-nuface-ultra-sunscreen-spf-60', 'Image Needs Review', 'workbook'),
  ('IMG-personal-care-dabur-nuface-nuface-ultra-sunscreen-spf-60', 'Manual Check', 'workbook'),
  ('IMG-personal-care-dabur-dabur-red-pulling-oil', 'Oral care oil', 'workbook'),
  ('IMG-personal-care-dabur-dabur-red-pulling-oil', 'Oil', 'workbook'),
  ('IMG-personal-care-dabur-dabur-red-pulling-oil', 'Image Needs Review', 'workbook'),
  ('IMG-personal-care-dabur-dabur-red-pulling-oil', 'Manual Check', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-gentle-baby-shampoo', 'Baby shampoo', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-gentle-baby-shampoo', 'Shampoo', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-gentle-baby-shampoo', 'Image Needs Review', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-gentle-baby-shampoo', 'Manual Check', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-baby-powder', 'Baby powder', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-baby-powder', 'Powder', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-baby-powder', 'Image Needs Review', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-baby-powder', 'Manual Check', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-gentle-baby-soap', 'Baby soap', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-gentle-baby-soap', 'Soap', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-gentle-baby-soap', 'Image Needs Review', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-gentle-baby-soap', 'Manual Check', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-baby-lotion', 'Baby lotion', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-baby-lotion', 'Lotion', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-baby-lotion', 'Image Needs Review', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-baby-lotion', 'Manual Check', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-baby-cream', 'Baby cream', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-baby-cream', 'Cream', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-baby-cream', 'Image Needs Review', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-baby-cream', 'Manual Check', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-head-to-toe-baby-wash-with-pure-cow-ghee', 'Baby wash', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-head-to-toe-baby-wash-with-pure-cow-ghee', 'Wash', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-head-to-toe-baby-wash-with-pure-cow-ghee', 'Image Needs Review', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-head-to-toe-baby-wash-with-pure-cow-ghee', 'Manual Check', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-baby-lotion-with-pure-cow-ghee', 'Baby lotion', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-baby-lotion-with-pure-cow-ghee', 'Lotion', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-baby-lotion-with-pure-cow-ghee', 'Image Needs Review', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-baby-lotion-with-pure-cow-ghee', 'Manual Check', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-baby-cream-with-pure-cow-ghee', 'Baby cream', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-baby-cream-with-pure-cow-ghee', 'Cream', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-baby-cream-with-pure-cow-ghee', 'Image Needs Review', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-baby-cream-with-pure-cow-ghee', 'Manual Check', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-baby-bar-with-pure-cow-ghee', 'Baby bathing bar', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-baby-bar-with-pure-cow-ghee', 'Bar', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-baby-bar-with-pure-cow-ghee', 'Image Needs Review', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-baby-bar-with-pure-cow-ghee', 'Manual Check', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-happy-baby-gift-pack-5-in-1', 'Baby gift pack', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-happy-baby-gift-pack-5-in-1', 'Kit', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-happy-baby-gift-pack-5-in-1', 'Image Needs Review', 'workbook'),
  ('IMG-baby-care-himalaya-baby-himalaya-happy-baby-gift-pack-5-in-1', 'Manual Check', 'workbook'),
  ('IMG-baby-care-johnson-s-baby-johnson-s-baby-shampoo', 'Baby shampoo', 'workbook'),
  ('IMG-baby-care-johnson-s-baby-johnson-s-baby-shampoo', 'Shampoo', 'workbook'),
  ('IMG-baby-care-johnson-s-baby-johnson-s-baby-shampoo', 'Image Needs Review', 'workbook'),
  ('IMG-baby-care-johnson-s-baby-johnson-s-baby-shampoo', 'Manual Check', 'workbook'),
  ('IMG-baby-care-johnson-s-baby-johnson-s-baby-oil', 'Baby oil', 'workbook'),
  ('IMG-baby-care-johnson-s-baby-johnson-s-baby-oil', 'Oil', 'workbook'),
  ('IMG-baby-care-johnson-s-baby-johnson-s-baby-oil', 'Image Needs Review', 'workbook'),
  ('IMG-baby-care-johnson-s-baby-johnson-s-baby-oil', 'Manual Check', 'workbook'),
  ('IMG-baby-care-johnson-s-baby-johnson-s-baby-powder', 'Baby powder', 'workbook'),
  ('IMG-baby-care-johnson-s-baby-johnson-s-baby-powder', 'Powder', 'workbook'),
  ('IMG-baby-care-johnson-s-baby-johnson-s-baby-powder', 'Image Needs Review', 'workbook'),
  ('IMG-baby-care-johnson-s-baby-johnson-s-baby-powder', 'Manual Check', 'workbook'),
  ('IMG-baby-care-johnson-s-baby-johnson-s-baby-soap', 'Baby soap', 'workbook'),
  ('IMG-baby-care-johnson-s-baby-johnson-s-baby-soap', 'Soap', 'workbook'),
  ('IMG-baby-care-johnson-s-baby-johnson-s-baby-soap', 'Image Needs Review', 'workbook'),
  ('IMG-baby-care-johnson-s-baby-johnson-s-baby-soap', 'Manual Check', 'workbook'),
  ('IMG-baby-care-johnson-s-baby-johnson-s-baby-lotion', 'Baby lotion', 'workbook'),
  ('IMG-baby-care-johnson-s-baby-johnson-s-baby-lotion', 'Lotion', 'workbook'),
  ('IMG-baby-care-johnson-s-baby-johnson-s-baby-lotion', 'Image Needs Review', 'workbook'),
  ('IMG-baby-care-johnson-s-baby-johnson-s-baby-lotion', 'Manual Check', 'workbook'),
  ('IMG-baby-care-johnson-s-baby-johnson-s-baby-wipes', 'Baby wipes', 'workbook'),
  ('IMG-baby-care-johnson-s-baby-johnson-s-baby-wipes', 'Wipes', 'workbook'),
  ('IMG-baby-care-johnson-s-baby-johnson-s-baby-wipes', 'Image Needs Review', 'workbook'),
  ('IMG-baby-care-johnson-s-baby-johnson-s-baby-wipes', 'Manual Check', 'workbook'),
  ('IMG-baby-care-johnson-s-baby-johnson-s-baby-gift-set-5-items-green', 'Baby gift set', 'workbook'),
  ('IMG-baby-care-johnson-s-baby-johnson-s-baby-gift-set-5-items-green', 'Gift set', 'workbook'),
  ('IMG-baby-care-johnson-s-baby-johnson-s-baby-gift-set-5-items-green', 'Image Needs Review', 'workbook'),
  ('IMG-baby-care-johnson-s-baby-johnson-s-baby-gift-set-5-items-green', 'Manual Check', 'workbook'),
  ('IMG-baby-care-mamaearth-mamaearth-milky-soft-diaper-rash-cream', 'Diaper rash cream', 'workbook'),
  ('IMG-baby-care-mamaearth-mamaearth-milky-soft-diaper-rash-cream', 'Cream', 'workbook'),
  ('IMG-baby-care-mamaearth-mamaearth-milky-soft-diaper-rash-cream', 'Image Needs Review', 'workbook'),
  ('IMG-baby-care-mamaearth-mamaearth-milky-soft-diaper-rash-cream', 'Manual Check', 'workbook'),
  ('IMG-baby-care-mamaearth-mamaearth-moisturizing-daily-lotion-for-babies', 'Baby lotion', 'workbook'),
  ('IMG-baby-care-mamaearth-mamaearth-moisturizing-daily-lotion-for-babies', 'Lotion', 'workbook'),
  ('IMG-baby-care-mamaearth-mamaearth-moisturizing-daily-lotion-for-babies', 'Image Needs Review', 'workbook'),
  ('IMG-baby-care-mamaearth-mamaearth-moisturizing-daily-lotion-for-babies', 'Manual Check', 'workbook'),
  ('IMG-baby-care-philips-avent-philips-avent-natural-baby-feeding-bottle', 'Baby feeding bottle', 'workbook'),
  ('IMG-baby-care-philips-avent-philips-avent-natural-baby-feeding-bottle', 'Bottle', 'workbook'),
  ('IMG-baby-care-philips-avent-philips-avent-natural-baby-feeding-bottle', 'Image Needs Review', 'workbook'),
  ('IMG-baby-care-philips-avent-philips-avent-natural-baby-feeding-bottle', 'Manual Check', 'workbook'),
  ('IMG-nutrition-abbott-ensure-nutritional-powder', 'Adult nutrition', 'workbook'),
  ('IMG-nutrition-abbott-ensure-nutritional-powder', 'Powder', 'workbook'),
  ('IMG-nutrition-abbott-ensure-nutritional-powder', 'Image Needs Review', 'workbook'),
  ('IMG-nutrition-abbott-ensure-nutritional-powder', 'Manual Check', 'workbook'),
  ('IMG-nutrition-abbott-pediasure-nutritional-powder', 'Child nutrition', 'workbook'),
  ('IMG-nutrition-abbott-pediasure-nutritional-powder', 'Powder', 'workbook'),
  ('IMG-nutrition-abbott-pediasure-nutritional-powder', 'Image Needs Review', 'workbook'),
  ('IMG-nutrition-abbott-pediasure-nutritional-powder', 'Manual Check', 'workbook'),
  ('IMG-nutrition-abbott-glucerna-nutritional-powder', 'Diabetes nutrition', 'workbook'),
  ('IMG-nutrition-abbott-glucerna-nutritional-powder', 'Powder', 'workbook'),
  ('IMG-nutrition-abbott-glucerna-nutritional-powder', 'Image Needs Review', 'workbook'),
  ('IMG-nutrition-abbott-glucerna-nutritional-powder', 'Manual Check', 'workbook'),
  ('IMG-nutrition-abbott-similac-infant-formula', 'Infant nutrition', 'workbook'),
  ('IMG-nutrition-abbott-similac-infant-formula', 'Powder', 'workbook'),
  ('IMG-nutrition-abbott-similac-infant-formula', 'Image Needs Review', 'workbook'),
  ('IMG-nutrition-abbott-similac-infant-formula', 'Manual Check', 'workbook'),
  ('IMG-nutrition-abbott-pedialyte-oral-electrolyte-solution', 'Pediatric hydration nutrition', 'workbook'),
  ('IMG-nutrition-abbott-pedialyte-oral-electrolyte-solution', 'Liquid', 'workbook'),
  ('IMG-nutrition-abbott-pedialyte-oral-electrolyte-solution', 'Image Needs Review', 'workbook'),
  ('IMG-nutrition-abbott-pedialyte-oral-electrolyte-solution', 'Manual Check', 'workbook'),
  ('IMG-nutrition-muscleblaze-muscleblaze-biozyme-performance-whey-rich-chocolate', 'Protein nutrition', 'workbook'),
  ('IMG-nutrition-muscleblaze-muscleblaze-biozyme-performance-whey-rich-chocolate', 'Powder', 'workbook'),
  ('IMG-nutrition-muscleblaze-muscleblaze-biozyme-performance-whey-rich-chocolate', 'Image Needs Review', 'workbook'),
  ('IMG-nutrition-muscleblaze-muscleblaze-biozyme-performance-whey-rich-chocolate', 'Manual Check', 'workbook'),
  ('IMG-nutrition-muscleblaze-muscleblaze-biozyme-whey-kesar-kulfi', 'Protein nutrition', 'workbook'),
  ('IMG-nutrition-muscleblaze-muscleblaze-biozyme-whey-kesar-kulfi', 'Powder', 'workbook'),
  ('IMG-nutrition-muscleblaze-muscleblaze-biozyme-whey-kesar-kulfi', 'Image Needs Review', 'workbook'),
  ('IMG-nutrition-muscleblaze-muscleblaze-biozyme-whey-kesar-kulfi', 'Manual Check', 'workbook'),
  ('IMG-nutrition-healthkart-hk-vitals-healthkart-hk-vitals-multivitamin-fish-oil-combo', 'Nutrition supplement combo', 'workbook'),
  ('IMG-nutrition-healthkart-hk-vitals-healthkart-hk-vitals-multivitamin-fish-oil-combo', 'Capsules/Tablets', 'workbook'),
  ('IMG-nutrition-healthkart-hk-vitals-healthkart-hk-vitals-multivitamin-fish-oil-combo', 'Image Needs Review', 'workbook'),
  ('IMG-nutrition-healthkart-hk-vitals-healthkart-hk-vitals-multivitamin-fish-oil-combo', 'Manual Check', 'workbook'),
  ('IMG-nutrition-wellbeing-nutrition-wellbeing-nutrition-plant-protein-chocolate', 'Protein nutrition', 'workbook'),
  ('IMG-nutrition-wellbeing-nutrition-wellbeing-nutrition-plant-protein-chocolate', 'Powder', 'workbook'),
  ('IMG-nutrition-wellbeing-nutrition-wellbeing-nutrition-plant-protein-chocolate', 'Image Needs Review', 'workbook'),
  ('IMG-nutrition-wellbeing-nutrition-wellbeing-nutrition-plant-protein-chocolate', 'Manual Check', 'workbook'),
  ('IMG-nutrition-wellbeing-nutrition-wellbeing-nutrition-kids-superfuel', 'Kids nutrition', 'workbook'),
  ('IMG-nutrition-wellbeing-nutrition-wellbeing-nutrition-kids-superfuel', 'Powder', 'workbook'),
  ('IMG-nutrition-wellbeing-nutrition-wellbeing-nutrition-kids-superfuel', 'Image Needs Review', 'workbook'),
  ('IMG-nutrition-wellbeing-nutrition-wellbeing-nutrition-kids-superfuel', 'Manual Check', 'workbook'),
  ('IMG-nutrition-plix-plix-plant-protein-chocolate', 'Plant protein', 'workbook'),
  ('IMG-nutrition-plix-plix-plant-protein-chocolate', 'Powder', 'workbook'),
  ('IMG-nutrition-plix-plix-plant-protein-chocolate', 'Image Needs Review', 'workbook'),
  ('IMG-nutrition-plix-plix-plant-protein-chocolate', 'Manual Check', 'workbook'),
  ('IMG-nutrition-plix-plix-kids-grow-buddy-gummies', 'Kids nutrition', 'workbook'),
  ('IMG-nutrition-plix-plix-kids-grow-buddy-gummies', 'Gummies', 'workbook'),
  ('IMG-nutrition-plix-plix-kids-grow-buddy-gummies', 'Image Needs Review', 'workbook'),
  ('IMG-nutrition-plix-plix-kids-grow-buddy-gummies', 'Manual Check', 'workbook'),
  ('IMG-nutrition-plix-plix-fit-slim-smoothie', 'Meal replacement', 'workbook'),
  ('IMG-nutrition-plix-plix-fit-slim-smoothie', 'Powder', 'workbook'),
  ('IMG-nutrition-plix-plix-fit-slim-smoothie', 'Image Needs Review', 'workbook'),
  ('IMG-nutrition-plix-plix-fit-slim-smoothie', 'Manual Check', 'workbook'),
  ('IMG-nutrition-fast-up-fast-up-plant-protein-rich-chocolate', 'Plant protein', 'workbook'),
  ('IMG-nutrition-fast-up-fast-up-plant-protein-rich-chocolate', 'Powder', 'workbook'),
  ('IMG-nutrition-fast-up-fast-up-plant-protein-rich-chocolate', 'Image Needs Review', 'workbook'),
  ('IMG-nutrition-fast-up-fast-up-plant-protein-rich-chocolate', 'Manual Check', 'workbook'),
  ('IMG-nutrition-fast-up-fast-up-whey-advanced-rich-chocolate', 'Whey protein', 'workbook'),
  ('IMG-nutrition-fast-up-fast-up-whey-advanced-rich-chocolate', 'Powder', 'workbook'),
  ('IMG-nutrition-fast-up-fast-up-whey-advanced-rich-chocolate', 'Image Needs Review', 'workbook'),
  ('IMG-nutrition-fast-up-fast-up-whey-advanced-rich-chocolate', 'Manual Check', 'workbook'),
  ('IMG-nutrition-fast-up-fast-up-whey-essentials-chocolate', 'Whey protein', 'workbook'),
  ('IMG-nutrition-fast-up-fast-up-whey-essentials-chocolate', 'Powder', 'workbook'),
  ('IMG-nutrition-fast-up-fast-up-whey-essentials-chocolate', 'Image Needs Review', 'workbook'),
  ('IMG-nutrition-fast-up-fast-up-whey-essentials-chocolate', 'Manual Check', 'workbook'),
  ('IMG-nutrition-bigmuscles-bigmuscles-clean-protein-performance-whey', 'Whey protein', 'workbook'),
  ('IMG-nutrition-bigmuscles-bigmuscles-clean-protein-performance-whey', 'Powder', 'workbook'),
  ('IMG-nutrition-bigmuscles-bigmuscles-clean-protein-performance-whey', 'Image Needs Review', 'workbook'),
  ('IMG-nutrition-bigmuscles-bigmuscles-clean-protein-performance-whey', 'Manual Check', 'workbook'),
  ('IMG-nutrition-bigmuscles-bigmuscles-premium-gold-whey', 'Whey protein', 'workbook'),
  ('IMG-nutrition-bigmuscles-bigmuscles-premium-gold-whey', 'Powder', 'workbook'),
  ('IMG-nutrition-bigmuscles-bigmuscles-premium-gold-whey', 'Image Needs Review', 'workbook'),
  ('IMG-nutrition-bigmuscles-bigmuscles-premium-gold-whey', 'Manual Check', 'workbook'),
  ('IMG-nutrition-nutrabay-nutrabay-bioabsorb-whey-protein', 'Whey protein', 'workbook'),
  ('IMG-nutrition-nutrabay-nutrabay-bioabsorb-whey-protein', 'Powder', 'workbook'),
  ('IMG-nutrition-nutrabay-nutrabay-bioabsorb-whey-protein', 'Image Needs Review', 'workbook'),
  ('IMG-nutrition-nutrabay-nutrabay-bioabsorb-whey-protein', 'Manual Check', 'workbook'),
  ('IMG-nutrition-dabur-dabur-chyawanprash-awaleha', 'Health food', 'workbook'),
  ('IMG-nutrition-dabur-dabur-chyawanprash-awaleha', 'Awaleha', 'workbook'),
  ('IMG-nutrition-dabur-dabur-chyawanprash-awaleha', 'Image Needs Review', 'workbook'),
  ('IMG-nutrition-dabur-dabur-chyawanprash-awaleha', 'Manual Check', 'workbook'),
  ('IMG-daily-wellness-dabur-dabur-honey', 'Health food', 'workbook'),
  ('IMG-daily-wellness-dabur-dabur-honey', 'Honey', 'workbook'),
  ('IMG-daily-wellness-dabur-dabur-honey', 'Image Needs Review', 'workbook'),
  ('IMG-daily-wellness-dabur-dabur-honey', 'Manual Check', 'workbook'),
  ('IMG-daily-wellness-dabur-dabur-chyawanprash-awaleha', 'Health food', 'workbook'),
  ('IMG-daily-wellness-dabur-dabur-chyawanprash-awaleha', 'Awaleha', 'workbook'),
  ('IMG-daily-wellness-dabur-dabur-chyawanprash-awaleha', 'Image Needs Review', 'workbook'),
  ('IMG-daily-wellness-dabur-dabur-chyawanprash-awaleha', 'Manual Check', 'workbook'),
  ('IMG-daily-wellness-dabur-dabur-chyawanprakash-sugarfree', 'Health food', 'workbook'),
  ('IMG-daily-wellness-dabur-dabur-chyawanprakash-sugarfree', 'Awaleha', 'workbook'),
  ('IMG-daily-wellness-dabur-dabur-chyawanprakash-sugarfree', 'Image Needs Review', 'workbook'),
  ('IMG-daily-wellness-dabur-dabur-chyawanprakash-sugarfree', 'Manual Check', 'workbook'),
  ('IMG-daily-wellness-himalaya-himalaya-organic-ashwagandha', 'Herbal supplement', 'workbook'),
  ('IMG-daily-wellness-himalaya-himalaya-organic-ashwagandha', 'Capsules/Tablets', 'workbook'),
  ('IMG-daily-wellness-himalaya-himalaya-organic-ashwagandha', 'Image Needs Review', 'workbook'),
  ('IMG-daily-wellness-himalaya-himalaya-organic-ashwagandha', 'Manual Check', 'workbook'),
  ('IMG-daily-wellness-himalaya-himalaya-shilajit-capsules', 'Herbal supplement', 'workbook'),
  ('IMG-daily-wellness-himalaya-himalaya-shilajit-capsules', 'Capsules', 'workbook'),
  ('IMG-daily-wellness-himalaya-himalaya-shilajit-capsules', 'Image Needs Review', 'workbook'),
  ('IMG-daily-wellness-himalaya-himalaya-shilajit-capsules', 'Manual Check', 'workbook'),
  ('IMG-daily-wellness-healthkart-hk-vitals-hk-vitals-multivitamin', 'Multivitamin', 'workbook'),
  ('IMG-daily-wellness-healthkart-hk-vitals-hk-vitals-multivitamin', 'Tablet', 'workbook'),
  ('IMG-daily-wellness-healthkart-hk-vitals-hk-vitals-multivitamin', 'Image Needs Review', 'workbook'),
  ('IMG-daily-wellness-healthkart-hk-vitals-hk-vitals-multivitamin', 'Manual Check', 'workbook'),
  ('IMG-daily-wellness-healthkart-hk-vitals-hk-vitals-vitamin-c', 'Vitamin supplement', 'workbook'),
  ('IMG-daily-wellness-healthkart-hk-vitals-hk-vitals-vitamin-c', 'Tablet', 'workbook'),
  ('IMG-daily-wellness-healthkart-hk-vitals-hk-vitals-vitamin-c', 'Image Needs Review', 'workbook'),
  ('IMG-daily-wellness-healthkart-hk-vitals-hk-vitals-vitamin-c', 'Manual Check', 'workbook'),
  ('IMG-daily-wellness-healthkart-hk-vitals-hk-vitals-vitamin-d3', 'Vitamin supplement', 'workbook'),
  ('IMG-daily-wellness-healthkart-hk-vitals-hk-vitals-vitamin-d3', 'Tablet', 'workbook'),
  ('IMG-daily-wellness-healthkart-hk-vitals-hk-vitals-vitamin-d3', 'Image Needs Review', 'workbook'),
  ('IMG-daily-wellness-healthkart-hk-vitals-hk-vitals-vitamin-d3', 'Manual Check', 'workbook'),
  ('IMG-daily-wellness-healthkart-hk-vitals-hk-vitals-magnesium-glycinate', 'Mineral supplement', 'workbook'),
  ('IMG-daily-wellness-healthkart-hk-vitals-hk-vitals-magnesium-glycinate', 'Tablet', 'workbook'),
  ('IMG-daily-wellness-healthkart-hk-vitals-hk-vitals-magnesium-glycinate', 'Image Needs Review', 'workbook'),
  ('IMG-daily-wellness-healthkart-hk-vitals-hk-vitals-magnesium-glycinate', 'Manual Check', 'workbook'),
  ('IMG-daily-wellness-fast-up-fast-up-activate-multivitamin-orange', 'Multivitamin', 'workbook'),
  ('IMG-daily-wellness-fast-up-fast-up-activate-multivitamin-orange', 'Effervescent tablets', 'workbook'),
  ('IMG-daily-wellness-fast-up-fast-up-activate-multivitamin-orange', 'Image Needs Review', 'workbook'),
  ('IMG-daily-wellness-fast-up-fast-up-activate-multivitamin-orange', 'Manual Check', 'workbook'),
  ('IMG-daily-wellness-fast-up-fast-up-apple-cider-vinegar-green-apple', 'ACV supplement', 'workbook'),
  ('IMG-daily-wellness-fast-up-fast-up-apple-cider-vinegar-green-apple', 'Effervescent tablets', 'workbook'),
  ('IMG-daily-wellness-fast-up-fast-up-apple-cider-vinegar-green-apple', 'Image Needs Review', 'workbook'),
  ('IMG-daily-wellness-fast-up-fast-up-apple-cider-vinegar-green-apple', 'Manual Check', 'workbook'),
  ('IMG-daily-wellness-wellbeing-nutrition-wellbeing-nutrition-melts-energy', 'Oral strip supplement', 'workbook'),
  ('IMG-daily-wellness-wellbeing-nutrition-wellbeing-nutrition-melts-energy', 'Oral strips', 'workbook'),
  ('IMG-daily-wellness-wellbeing-nutrition-wellbeing-nutrition-melts-energy', 'Image Needs Review', 'workbook'),
  ('IMG-daily-wellness-wellbeing-nutrition-wellbeing-nutrition-melts-energy', 'Manual Check', 'workbook'),
  ('IMG-daily-wellness-wellbeing-nutrition-wellbeing-nutrition-melts-sleep', 'Oral strip supplement', 'workbook'),
  ('IMG-daily-wellness-wellbeing-nutrition-wellbeing-nutrition-melts-sleep', 'Oral strips', 'workbook'),
  ('IMG-daily-wellness-wellbeing-nutrition-wellbeing-nutrition-melts-sleep', 'Image Needs Review', 'workbook'),
  ('IMG-daily-wellness-wellbeing-nutrition-wellbeing-nutrition-melts-sleep', 'Manual Check', 'workbook'),
  ('IMG-daily-wellness-wellbeing-nutrition-wellbeing-nutrition-daily-fiber', 'Fiber supplement', 'workbook'),
  ('IMG-daily-wellness-wellbeing-nutrition-wellbeing-nutrition-daily-fiber', 'Powder', 'workbook'),
  ('IMG-daily-wellness-wellbeing-nutrition-wellbeing-nutrition-daily-fiber', 'Image Needs Review', 'workbook'),
  ('IMG-daily-wellness-wellbeing-nutrition-wellbeing-nutrition-daily-fiber', 'Manual Check', 'workbook'),
  ('IMG-daily-wellness-plix-plix-daily-greens', 'Greens supplement', 'workbook'),
  ('IMG-daily-wellness-plix-plix-daily-greens', 'Powder', 'workbook'),
  ('IMG-daily-wellness-plix-plix-daily-greens', 'Image Needs Review', 'workbook'),
  ('IMG-daily-wellness-plix-plix-daily-greens', 'Manual Check', 'workbook'),
  ('IMG-daily-wellness-plix-plix-apple-cider-vinegar-effervescent', 'ACV supplement', 'workbook'),
  ('IMG-daily-wellness-plix-plix-apple-cider-vinegar-effervescent', 'Effervescent tablets', 'workbook'),
  ('IMG-daily-wellness-plix-plix-apple-cider-vinegar-effervescent', 'Image Needs Review', 'workbook'),
  ('IMG-daily-wellness-plix-plix-apple-cider-vinegar-effervescent', 'Manual Check', 'workbook'),
  ('IMG-daily-wellness-kapiva-kapiva-aloe-vera-juice', 'Ayurvedic juice', 'workbook'),
  ('IMG-daily-wellness-kapiva-kapiva-aloe-vera-juice', 'Juice', 'workbook'),
  ('IMG-daily-wellness-kapiva-kapiva-aloe-vera-juice', 'Image Needs Review', 'workbook'),
  ('IMG-daily-wellness-kapiva-kapiva-aloe-vera-juice', 'Manual Check', 'workbook'),
  ('IMG-daily-wellness-kapiva-kapiva-amla-juice', 'Ayurvedic juice', 'workbook'),
  ('IMG-daily-wellness-kapiva-kapiva-amla-juice', 'Juice', 'workbook'),
  ('IMG-daily-wellness-kapiva-kapiva-amla-juice', 'Image Needs Review', 'workbook'),
  ('IMG-daily-wellness-kapiva-kapiva-amla-juice', 'Manual Check', 'workbook'),
  ('IMG-daily-wellness-organic-india-organic-india-tulsi-green-tea', 'Herbal tea', 'workbook'),
  ('IMG-daily-wellness-organic-india-organic-india-tulsi-green-tea', 'Tea bags', 'workbook'),
  ('IMG-daily-wellness-organic-india-organic-india-tulsi-green-tea', 'Image Needs Review', 'workbook'),
  ('IMG-daily-wellness-organic-india-organic-india-tulsi-green-tea', 'Manual Check', 'workbook'),
  ('IMG-daily-wellness-organic-india-organic-india-ashwagandha-capsules', 'Herbal supplement', 'workbook'),
  ('IMG-daily-wellness-organic-india-organic-india-ashwagandha-capsules', 'Capsules', 'workbook'),
  ('IMG-daily-wellness-organic-india-organic-india-ashwagandha-capsules', 'Image Needs Review', 'workbook'),
  ('IMG-daily-wellness-organic-india-organic-india-ashwagandha-capsules', 'Manual Check', 'workbook'),
  ('IMG-fitness-nutrition-muscleblaze-muscleblaze-biozyme-performance-whey-2-kg-rich-chocolate', 'Whey protein', 'workbook'),
  ('IMG-fitness-nutrition-muscleblaze-muscleblaze-biozyme-performance-whey-2-kg-rich-chocolate', 'Powder', 'workbook'),
  ('IMG-fitness-nutrition-muscleblaze-muscleblaze-biozyme-performance-whey-2-kg-rich-chocolate', 'Image Needs Review', 'workbook'),
  ('IMG-fitness-nutrition-muscleblaze-muscleblaze-biozyme-performance-whey-2-kg-rich-chocolate', 'Manual Check', 'workbook'),
  ('IMG-fitness-nutrition-muscleblaze-muscleblaze-biozyme-performance-whey-1-kg-rich-chocolate', 'Whey protein', 'workbook'),
  ('IMG-fitness-nutrition-muscleblaze-muscleblaze-biozyme-performance-whey-1-kg-rich-chocolate', 'Powder', 'workbook'),
  ('IMG-fitness-nutrition-muscleblaze-muscleblaze-biozyme-performance-whey-1-kg-rich-chocolate', 'Image Needs Review', 'workbook'),
  ('IMG-fitness-nutrition-muscleblaze-muscleblaze-biozyme-performance-whey-1-kg-rich-chocolate', 'Manual Check', 'workbook'),
  ('IMG-fitness-nutrition-muscleblaze-muscleblaze-biozyme-whey-kesar-kulfi', 'Whey protein', 'workbook'),
  ('IMG-fitness-nutrition-muscleblaze-muscleblaze-biozyme-whey-kesar-kulfi', 'Powder', 'workbook'),
  ('IMG-fitness-nutrition-muscleblaze-muscleblaze-biozyme-whey-kesar-kulfi', 'Image Needs Review', 'workbook'),
  ('IMG-fitness-nutrition-muscleblaze-muscleblaze-biozyme-whey-kesar-kulfi', 'Manual Check', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-whey-advanced-rich-chocolate', 'Whey protein', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-whey-advanced-rich-chocolate', 'Powder', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-whey-advanced-rich-chocolate', 'Image Needs Review', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-whey-advanced-rich-chocolate', 'Manual Check', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-whey-essentials-chocolate', 'Whey protein', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-whey-essentials-chocolate', 'Powder', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-whey-essentials-chocolate', 'Image Needs Review', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-whey-essentials-chocolate', 'Manual Check', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-plant-protein-rich-chocolate', 'Plant protein', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-plant-protein-rich-chocolate', 'Powder', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-plant-protein-rich-chocolate', 'Image Needs Review', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-plant-protein-rich-chocolate', 'Manual Check', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-bcaa-advanced-berry-lemonade', 'BCAA supplement', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-bcaa-advanced-berry-lemonade', 'Powder', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-bcaa-advanced-berry-lemonade', 'Image Needs Review', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-bcaa-advanced-berry-lemonade', 'Manual Check', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-essential-amino-acids-watermelon', 'EAA supplement', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-essential-amino-acids-watermelon', 'Powder', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-essential-amino-acids-watermelon', 'Image Needs Review', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-essential-amino-acids-watermelon', 'Manual Check', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-creatine-monohydrate-essentials', 'Creatine', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-creatine-monohydrate-essentials', 'Powder', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-creatine-monohydrate-essentials', 'Image Needs Review', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-creatine-monohydrate-essentials', 'Manual Check', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-pre-workout-watermelon', 'Pre-workout', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-pre-workout-watermelon', 'Powder', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-pre-workout-watermelon', 'Image Needs Review', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-pre-workout-watermelon', 'Manual Check', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-glutamine', 'Glutamine supplement', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-glutamine', 'Powder', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-glutamine', 'Image Needs Review', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-glutamine', 'Manual Check', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-sports-collagen-aam-panna', 'Sports collagen', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-sports-collagen-aam-panna', 'Powder', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-sports-collagen-aam-panna', 'Image Needs Review', 'workbook'),
  ('IMG-fitness-nutrition-fast-up-fast-up-sports-collagen-aam-panna', 'Manual Check', 'workbook'),
  ('IMG-fitness-nutrition-bigmuscles-bigmuscles-benchmark-creatine-monohydrate', 'Creatine', 'workbook'),
  ('IMG-fitness-nutrition-bigmuscles-bigmuscles-benchmark-creatine-monohydrate', 'Powder', 'workbook'),
  ('IMG-fitness-nutrition-bigmuscles-bigmuscles-benchmark-creatine-monohydrate', 'Image Needs Review', 'workbook'),
  ('IMG-fitness-nutrition-bigmuscles-bigmuscles-benchmark-creatine-monohydrate', 'Manual Check', 'workbook'),
  ('IMG-fitness-nutrition-bigmuscles-bigmuscles-clean-protein-performance-whey', 'Whey protein', 'workbook'),
  ('IMG-fitness-nutrition-bigmuscles-bigmuscles-clean-protein-performance-whey', 'Powder', 'workbook'),
  ('IMG-fitness-nutrition-bigmuscles-bigmuscles-clean-protein-performance-whey', 'Image Needs Review', 'workbook'),
  ('IMG-fitness-nutrition-bigmuscles-bigmuscles-clean-protein-performance-whey', 'Manual Check', 'workbook'),
  ('IMG-fitness-nutrition-bigmuscles-bigmuscles-premium-gold-whey-creatine', 'Whey + creatine combo', 'workbook'),
  ('IMG-fitness-nutrition-bigmuscles-bigmuscles-premium-gold-whey-creatine', 'Combo', 'workbook'),
  ('IMG-fitness-nutrition-bigmuscles-bigmuscles-premium-gold-whey-creatine', 'Image Needs Review', 'workbook'),
  ('IMG-fitness-nutrition-bigmuscles-bigmuscles-premium-gold-whey-creatine', 'Manual Check', 'workbook'),
  ('IMG-fitness-nutrition-bigmuscles-bigmuscles-nitra-isolate-creatine', 'Whey + creatine combo', 'workbook'),
  ('IMG-fitness-nutrition-bigmuscles-bigmuscles-nitra-isolate-creatine', 'Combo', 'workbook'),
  ('IMG-fitness-nutrition-bigmuscles-bigmuscles-nitra-isolate-creatine', 'Image Needs Review', 'workbook'),
  ('IMG-fitness-nutrition-bigmuscles-bigmuscles-nitra-isolate-creatine', 'Manual Check', 'workbook'),
  ('IMG-fitness-nutrition-bigmuscles-bigmuscles-real-bcaa', 'BCAA supplement', 'workbook'),
  ('IMG-fitness-nutrition-bigmuscles-bigmuscles-real-bcaa', 'Powder', 'workbook'),
  ('IMG-fitness-nutrition-bigmuscles-bigmuscles-real-bcaa', 'Image Needs Review', 'workbook'),
  ('IMG-fitness-nutrition-bigmuscles-bigmuscles-real-bcaa', 'Manual Check', 'workbook'),
  ('IMG-fitness-nutrition-bigmuscles-bigmuscles-essential-eaa', 'EAA supplement', 'workbook'),
  ('IMG-fitness-nutrition-bigmuscles-bigmuscles-essential-eaa', 'Powder', 'workbook'),
  ('IMG-fitness-nutrition-bigmuscles-bigmuscles-essential-eaa', 'Image Needs Review', 'workbook'),
  ('IMG-fitness-nutrition-bigmuscles-bigmuscles-essential-eaa', 'Manual Check', 'workbook'),
  ('IMG-fitness-nutrition-wellbeing-nutrition-wellbeing-nutrition-whey-protein', 'Whey protein', 'workbook'),
  ('IMG-fitness-nutrition-wellbeing-nutrition-wellbeing-nutrition-whey-protein', 'Powder', 'workbook'),
  ('IMG-fitness-nutrition-wellbeing-nutrition-wellbeing-nutrition-whey-protein', 'Image Needs Review', 'workbook'),
  ('IMG-fitness-nutrition-wellbeing-nutrition-wellbeing-nutrition-whey-protein', 'Manual Check', 'workbook'),
  ('IMG-fitness-nutrition-plix-plix-plant-protein', 'Plant protein', 'workbook'),
  ('IMG-fitness-nutrition-plix-plix-plant-protein', 'Powder', 'workbook'),
  ('IMG-fitness-nutrition-plix-plix-plant-protein', 'Image Needs Review', 'workbook'),
  ('IMG-fitness-nutrition-plix-plix-plant-protein', 'Manual Check', 'workbook'),
  ('IMG-hydration-fdc-electral-electral-ors-oral-granules-21-8-g', 'ORS', 'workbook'),
  ('IMG-hydration-fdc-electral-electral-ors-oral-granules-21-8-g', 'Powder sachet', 'workbook'),
  ('IMG-hydration-fdc-electral-electral-ors-oral-granules-21-8-g', 'Image Needs Review', 'workbook'),
  ('IMG-hydration-fdc-electral-electral-ors-oral-granules-21-8-g', 'Manual Check', 'workbook'),
  ('IMG-hydration-fdc-electral-electral-forte-oral-rehydration-salts-6-g', 'ORS', 'workbook'),
  ('IMG-hydration-fdc-electral-electral-forte-oral-rehydration-salts-6-g', 'Powder sachet', 'workbook'),
  ('IMG-hydration-fdc-electral-electral-forte-oral-rehydration-salts-6-g', 'Image Needs Review', 'workbook'),
  ('IMG-hydration-fdc-electral-electral-forte-oral-rehydration-salts-6-g', 'Manual Check', 'workbook'),
  ('IMG-hydration-enerzal-enerzal-energy-drink-powder-orange-500-g', 'Electrolyte drink powder', 'workbook'),
  ('IMG-hydration-enerzal-enerzal-energy-drink-powder-orange-500-g', 'Powder', 'workbook'),
  ('IMG-hydration-enerzal-enerzal-energy-drink-powder-orange-500-g', 'Image Needs Review', 'workbook'),
  ('IMG-hydration-enerzal-enerzal-energy-drink-powder-orange-500-g', 'Manual Check', 'workbook'),
  ('IMG-hydration-enerzal-enerzal-energy-drink-powder-lime-500-g', 'Electrolyte drink powder', 'workbook'),
  ('IMG-hydration-enerzal-enerzal-energy-drink-powder-lime-500-g', 'Powder', 'workbook'),
  ('IMG-hydration-enerzal-enerzal-energy-drink-powder-lime-500-g', 'Image Needs Review', 'workbook'),
  ('IMG-hydration-enerzal-enerzal-energy-drink-powder-lime-500-g', 'Manual Check', 'workbook'),
  ('IMG-hydration-enerzal-enerzal-zero-hydration-drink-powder-7-sachets', 'Electrolyte drink powder', 'workbook'),
  ('IMG-hydration-enerzal-enerzal-zero-hydration-drink-powder-7-sachets', 'Powder sachets', 'workbook'),
  ('IMG-hydration-enerzal-enerzal-zero-hydration-drink-powder-7-sachets', 'Image Needs Review', 'workbook'),
  ('IMG-hydration-enerzal-enerzal-zero-hydration-drink-powder-7-sachets', 'Manual Check', 'workbook'),
  ('IMG-hydration-enerzal-enerzal-zero-energy-drink-liquid-400-ml', 'Hydration drink', 'workbook'),
  ('IMG-hydration-enerzal-enerzal-zero-energy-drink-liquid-400-ml', 'Ready-to-drink', 'workbook'),
  ('IMG-hydration-enerzal-enerzal-zero-energy-drink-liquid-400-ml', 'Image Needs Review', 'workbook'),
  ('IMG-hydration-enerzal-enerzal-zero-energy-drink-liquid-400-ml', 'Manual Check', 'workbook'),
  ('IMG-hydration-enerzal-enerzal-orange-50-g', 'Electrolyte drink powder', 'workbook'),
  ('IMG-hydration-enerzal-enerzal-orange-50-g', 'Powder', 'workbook'),
  ('IMG-hydration-enerzal-enerzal-orange-50-g', 'Image Needs Review', 'workbook'),
  ('IMG-hydration-enerzal-enerzal-orange-50-g', 'Manual Check', 'workbook'),
  ('IMG-hydration-enerzal-enerzal-orange-100-g', 'Electrolyte drink powder', 'workbook'),
  ('IMG-hydration-enerzal-enerzal-orange-100-g', 'Powder', 'workbook'),
  ('IMG-hydration-enerzal-enerzal-orange-100-g', 'Image Needs Review', 'workbook'),
  ('IMG-hydration-enerzal-enerzal-orange-100-g', 'Manual Check', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-zero-sugar-ice-current', 'Electrolyte tablets', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-zero-sugar-ice-current', 'Effervescent tablets', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-zero-sugar-ice-current', 'Image Needs Review', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-zero-sugar-ice-current', 'Manual Check', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-zero-lime-lemon', 'Electrolyte tablets', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-zero-lime-lemon', 'Effervescent tablets', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-zero-lime-lemon', 'Image Needs Review', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-zero-lime-lemon', 'Manual Check', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-zero-sugar-sticks-assorted', 'Electrolyte sticks', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-zero-sugar-sticks-assorted', 'Powder sticks', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-zero-sugar-sticks-assorted', 'Image Needs Review', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-zero-sugar-sticks-assorted', 'Manual Check', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-zero-sugar-sticks-kiwi-berry', 'Electrolyte sticks', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-zero-sugar-sticks-kiwi-berry', 'Powder sticks', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-zero-sugar-sticks-kiwi-berry', 'Image Needs Review', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-zero-sugar-sticks-kiwi-berry', 'Manual Check', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-zero-sugar-sticks-mango-samba', 'Electrolyte sticks', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-zero-sugar-sticks-mango-samba', 'Powder sticks', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-zero-sugar-sticks-mango-samba', 'Image Needs Review', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-zero-sugar-sticks-mango-samba', 'Manual Check', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-salts-high-sodium-orange-5s', 'Electrolyte salts', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-salts-high-sodium-orange-5s', 'Powder sticks', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-salts-high-sodium-orange-5s', 'Image Needs Review', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-salts-high-sodium-orange-5s', 'Manual Check', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-salts-high-sodium-lemonade-5s', 'Electrolyte salts', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-salts-high-sodium-lemonade-5s', 'Powder sticks', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-salts-high-sodium-lemonade-5s', 'Image Needs Review', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-salts-high-sodium-lemonade-5s', 'Manual Check', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-stick-orange', 'Electrolyte stick', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-stick-orange', 'Powder stick', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-stick-orange', 'Image Needs Review', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-stick-orange', 'Manual Check', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-low-sugar-aam-panna', 'Electrolyte tablets', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-low-sugar-aam-panna', 'Effervescent tablets', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-low-sugar-aam-panna', 'Image Needs Review', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-low-sugar-aam-panna', 'Manual Check', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-low-sugar-berry', 'Electrolyte tablets', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-low-sugar-berry', 'Effervescent tablets', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-low-sugar-berry', 'Image Needs Review', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-low-sugar-berry', 'Manual Check', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-low-sugar-cola', 'Electrolyte tablets', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-low-sugar-cola', 'Effervescent tablets', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-low-sugar-cola', 'Image Needs Review', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-low-sugar-cola', 'Manual Check', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-low-sugar-orange', 'Electrolyte tablets', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-low-sugar-orange', 'Effervescent tablets', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-low-sugar-orange', 'Image Needs Review', 'workbook'),
  ('IMG-hydration-fast-up-fast-up-reload-low-sugar-orange', 'Manual Check', 'workbook'),
  ('IMG-digestive-health-dabur-dabur-pudin-hara-pearls', 'Digestive product', 'workbook'),
  ('IMG-digestive-health-dabur-dabur-pudin-hara-pearls', 'Pearls', 'workbook'),
  ('IMG-digestive-health-dabur-dabur-pudin-hara-pearls', 'Image Needs Review', 'workbook'),
  ('IMG-digestive-health-dabur-dabur-pudin-hara-pearls', 'Manual Check', 'workbook'),
  ('IMG-digestive-health-dabur-dabur-pudin-hara-active', 'Digestive product', 'workbook'),
  ('IMG-digestive-health-dabur-dabur-pudin-hara-active', 'Liquid/Gel', 'workbook'),
  ('IMG-digestive-health-dabur-dabur-pudin-hara-active', 'Image Needs Review', 'workbook'),
  ('IMG-digestive-health-dabur-dabur-pudin-hara-active', 'Manual Check', 'workbook'),
  ('IMG-digestive-health-dabur-dabur-hajmola-regular', 'Digestive candy/tablet', 'workbook'),
  ('IMG-digestive-health-dabur-dabur-hajmola-regular', 'Tablets', 'workbook'),
  ('IMG-digestive-health-dabur-dabur-hajmola-regular', 'Image Needs Review', 'workbook'),
  ('IMG-digestive-health-dabur-dabur-hajmola-regular', 'Manual Check', 'workbook'),
  ('IMG-digestive-health-dabur-dabur-hajmola-imli', 'Digestive candy/tablet', 'workbook'),
  ('IMG-digestive-health-dabur-dabur-hajmola-imli', 'Tablets', 'workbook'),
  ('IMG-digestive-health-dabur-dabur-hajmola-imli', 'Image Needs Review', 'workbook'),
  ('IMG-digestive-health-dabur-dabur-hajmola-imli', 'Manual Check', 'workbook'),
  ('IMG-digestive-health-dabur-dabur-sat-isabgol', 'Fibre supplement', 'workbook'),
  ('IMG-digestive-health-dabur-dabur-sat-isabgol', 'Powder', 'workbook'),
  ('IMG-digestive-health-dabur-dabur-sat-isabgol', 'Image Needs Review', 'workbook'),
  ('IMG-digestive-health-dabur-dabur-sat-isabgol', 'Manual Check', 'workbook'),
  ('IMG-digestive-health-kapiva-kapiva-triphala-juice', 'Ayurvedic digestive', 'workbook'),
  ('IMG-digestive-health-kapiva-kapiva-triphala-juice', 'Juice', 'workbook'),
  ('IMG-digestive-health-kapiva-kapiva-triphala-juice', 'Image Needs Review', 'workbook'),
  ('IMG-digestive-health-kapiva-kapiva-triphala-juice', 'Manual Check', 'workbook'),
  ('IMG-digestive-health-kapiva-kapiva-aloe-vera-juice', 'Ayurvedic digestive', 'workbook'),
  ('IMG-digestive-health-kapiva-kapiva-aloe-vera-juice', 'Juice', 'workbook'),
  ('IMG-digestive-health-kapiva-kapiva-aloe-vera-juice', 'Image Needs Review', 'workbook'),
  ('IMG-digestive-health-kapiva-kapiva-aloe-vera-juice', 'Manual Check', 'workbook'),
  ('IMG-digestive-health-kapiva-kapiva-amla-juice', 'Ayurvedic digestive', 'workbook'),
  ('IMG-digestive-health-kapiva-kapiva-amla-juice', 'Juice', 'workbook'),
  ('IMG-digestive-health-kapiva-kapiva-amla-juice', 'Image Needs Review', 'workbook'),
  ('IMG-digestive-health-kapiva-kapiva-amla-juice', 'Manual Check', 'workbook'),
  ('IMG-digestive-health-kapiva-kapiva-dia-free-juice', 'Ayurvedic juice', 'workbook'),
  ('IMG-digestive-health-kapiva-kapiva-dia-free-juice', 'Juice', 'workbook'),
  ('IMG-digestive-health-kapiva-kapiva-dia-free-juice', 'Image Needs Review', 'workbook'),
  ('IMG-digestive-health-kapiva-kapiva-dia-free-juice', 'Manual Check', 'workbook'),
  ('IMG-digestive-health-himalaya-himalaya-gasex-tablet', 'Ayurvedic digestive', 'workbook'),
  ('IMG-digestive-health-himalaya-himalaya-gasex-tablet', 'Tablet', 'workbook'),
  ('IMG-digestive-health-himalaya-himalaya-gasex-tablet', 'Image Needs Review', 'workbook'),
  ('IMG-digestive-health-himalaya-himalaya-gasex-tablet', 'Manual Check', 'workbook'),
  ('IMG-digestive-health-himalaya-himalaya-bael-tablet', 'Ayurvedic digestive', 'workbook'),
  ('IMG-digestive-health-himalaya-himalaya-bael-tablet', 'Tablet', 'workbook'),
  ('IMG-digestive-health-himalaya-himalaya-bael-tablet', 'Image Needs Review', 'workbook'),
  ('IMG-digestive-health-himalaya-himalaya-bael-tablet', 'Manual Check', 'workbook'),
  ('IMG-digestive-health-himalaya-himalaya-triphala-tablet', 'Ayurvedic digestive', 'workbook'),
  ('IMG-digestive-health-himalaya-himalaya-triphala-tablet', 'Tablet', 'workbook'),
  ('IMG-digestive-health-himalaya-himalaya-triphala-tablet', 'Image Needs Review', 'workbook'),
  ('IMG-digestive-health-himalaya-himalaya-triphala-tablet', 'Manual Check', 'workbook'),
  ('IMG-digestive-health-healthkart-hk-vitals-hk-vitals-pre-and-probiotics', 'Probiotic supplement', 'workbook'),
  ('IMG-digestive-health-healthkart-hk-vitals-hk-vitals-pre-and-probiotics', 'Capsules', 'workbook'),
  ('IMG-digestive-health-healthkart-hk-vitals-hk-vitals-pre-and-probiotics', 'Image Needs Review', 'workbook'),
  ('IMG-digestive-health-healthkart-hk-vitals-hk-vitals-pre-and-probiotics', 'Manual Check', 'workbook'),
  ('IMG-digestive-health-simply-herbal-simply-herbal-probiotics-25-billion', 'Probiotic supplement', 'workbook'),
  ('IMG-digestive-health-simply-herbal-simply-herbal-probiotics-25-billion', 'Capsules', 'workbook'),
  ('IMG-digestive-health-simply-herbal-simply-herbal-probiotics-25-billion', 'Image Needs Review', 'workbook'),
  ('IMG-digestive-health-simply-herbal-simply-herbal-probiotics-25-billion', 'Manual Check', 'workbook'),
  ('IMG-digestive-health-simply-herbal-simply-herbal-probiotics-50-billion', 'Probiotic supplement', 'workbook'),
  ('IMG-digestive-health-simply-herbal-simply-herbal-probiotics-50-billion', 'Capsules', 'workbook'),
  ('IMG-digestive-health-simply-herbal-simply-herbal-probiotics-50-billion', 'Image Needs Review', 'workbook'),
  ('IMG-digestive-health-simply-herbal-simply-herbal-probiotics-50-billion', 'Manual Check', 'workbook'),
  ('IMG-digestive-health-now-now-probiotic-10-50-billion', 'Probiotic supplement', 'workbook'),
  ('IMG-digestive-health-now-now-probiotic-10-50-billion', 'Veg capsules', 'workbook'),
  ('IMG-digestive-health-now-now-probiotic-10-50-billion', 'Image Needs Review', 'workbook'),
  ('IMG-digestive-health-now-now-probiotic-10-50-billion', 'Manual Check', 'workbook'),
  ('IMG-digestive-health-now-now-super-enzymes', 'Digestive enzyme supplement', 'workbook'),
  ('IMG-digestive-health-now-now-super-enzymes', 'Capsules', 'workbook'),
  ('IMG-digestive-health-now-now-super-enzymes', 'Image Needs Review', 'workbook'),
  ('IMG-digestive-health-now-now-super-enzymes', 'Manual Check', 'workbook'),
  ('IMG-digestive-health-nutrabay-nutrabay-bioabsorb-whey-protein-with-prodifi-blend', 'Protein with digestive support', 'workbook'),
  ('IMG-digestive-health-nutrabay-nutrabay-bioabsorb-whey-protein-with-prodifi-blend', 'Powder', 'workbook'),
  ('IMG-digestive-health-nutrabay-nutrabay-bioabsorb-whey-protein-with-prodifi-blend', 'Image Needs Review', 'workbook'),
  ('IMG-digestive-health-nutrabay-nutrabay-bioabsorb-whey-protein-with-prodifi-blend', 'Manual Check', 'workbook'),
  ('IMG-digestive-health-ghost-ghost-greens-superfood', 'Greens/probiotic supplement', 'workbook'),
  ('IMG-digestive-health-ghost-ghost-greens-superfood', 'Powder', 'workbook'),
  ('IMG-digestive-health-ghost-ghost-greens-superfood', 'Image Needs Review', 'workbook'),
  ('IMG-digestive-health-ghost-ghost-greens-superfood', 'Manual Check', 'workbook'),
  ('IMG-digestive-health-wellbeing-nutrition-wellbeing-nutrition-daily-fiber', 'Fibre supplement', 'workbook'),
  ('IMG-digestive-health-wellbeing-nutrition-wellbeing-nutrition-daily-fiber', 'Powder', 'workbook'),
  ('IMG-digestive-health-wellbeing-nutrition-wellbeing-nutrition-daily-fiber', 'Image Needs Review', 'workbook'),
  ('IMG-digestive-health-wellbeing-nutrition-wellbeing-nutrition-daily-fiber', 'Manual Check', 'workbook'),
  ('IMG-heart-health-healthkart-hk-vitals-hk-vitals-fish-oil-1000mg-with-epa-dha', 'Omega-3 supplement', 'workbook'),
  ('IMG-heart-health-healthkart-hk-vitals-hk-vitals-fish-oil-1000mg-with-epa-dha', 'Capsules', 'workbook'),
  ('IMG-heart-health-healthkart-hk-vitals-hk-vitals-fish-oil-1000mg-with-epa-dha', 'Image Needs Review', 'workbook'),
  ('IMG-heart-health-healthkart-hk-vitals-hk-vitals-fish-oil-1000mg-with-epa-dha', 'Manual Check', 'workbook'),
  ('IMG-heart-health-truebasics-truebasics-ultra-omega-3', 'Omega-3 supplement', 'workbook'),
  ('IMG-heart-health-truebasics-truebasics-ultra-omega-3', 'Capsules', 'workbook'),
  ('IMG-heart-health-truebasics-truebasics-ultra-omega-3', 'Image Needs Review', 'workbook'),
  ('IMG-heart-health-truebasics-truebasics-ultra-omega-3', 'Manual Check', 'workbook'),
  ('IMG-heart-health-truebasics-truebasics-heart-omega-3-antarctic-krill-oil-op', 'Krill oil supplement', 'workbook'),
  ('IMG-heart-health-truebasics-truebasics-heart-omega-3-antarctic-krill-oil-op', 'Capsules', 'workbook'),
  ('IMG-heart-health-truebasics-truebasics-heart-omega-3-antarctic-krill-oil-op', 'Image Needs Review', 'workbook'),
  ('IMG-heart-health-truebasics-truebasics-heart-omega-3-antarctic-krill-oil-op', 'Manual Check', 'workbook'),
  ('IMG-heart-health-myprotein-myprotein-essential-omega-3', 'Omega-3 supplement', 'workbook'),
  ('IMG-heart-health-myprotein-myprotein-essential-omega-3', 'Softgels', 'workbook'),
  ('IMG-heart-health-myprotein-myprotein-essential-omega-3', 'Image Needs Review', 'workbook'),
  ('IMG-heart-health-myprotein-myprotein-essential-omega-3', 'Manual Check', 'workbook'),
  ('IMG-heart-health-best-naturals-best-naturals-fish-oil-1000-mg-epa-dha', 'Omega-3 supplement', 'workbook'),
  ('IMG-heart-health-best-naturals-best-naturals-fish-oil-1000-mg-epa-dha', 'Softgels', 'workbook'),
  ('IMG-heart-health-best-naturals-best-naturals-fish-oil-1000-mg-epa-dha', 'Image Needs Review', 'workbook'),
  ('IMG-heart-health-best-naturals-best-naturals-fish-oil-1000-mg-epa-dha', 'Manual Check', 'workbook'),
  ('IMG-heart-health-healthaid-healthaid-omega-3', 'Omega-3 supplement', 'workbook'),
  ('IMG-heart-health-healthaid-healthaid-omega-3', 'Capsules', 'workbook'),
  ('IMG-heart-health-healthaid-healthaid-omega-3', 'Image Needs Review', 'workbook'),
  ('IMG-heart-health-healthaid-healthaid-omega-3', 'Manual Check', 'workbook'),
  ('IMG-heart-health-kaged-muscle-kaged-muscle-omega-3', 'Omega-3 supplement', 'workbook'),
  ('IMG-heart-health-kaged-muscle-kaged-muscle-omega-3', 'Softgels', 'workbook'),
  ('IMG-heart-health-kaged-muscle-kaged-muscle-omega-3', 'Image Needs Review', 'workbook'),
  ('IMG-heart-health-kaged-muscle-kaged-muscle-omega-3', 'Manual Check', 'workbook'),
  ('IMG-heart-health-wellbeing-nutrition-wellbeing-nutrition-omega-fish-oil', 'Omega-3 supplement', 'workbook'),
  ('IMG-heart-health-wellbeing-nutrition-wellbeing-nutrition-omega-fish-oil', 'Capsules', 'workbook'),
  ('IMG-heart-health-wellbeing-nutrition-wellbeing-nutrition-omega-fish-oil', 'Image Needs Review', 'workbook'),
  ('IMG-heart-health-wellbeing-nutrition-wellbeing-nutrition-omega-fish-oil', 'Manual Check', 'workbook'),
  ('IMG-heart-health-wellbeing-nutrition-wellbeing-nutrition-coq10', 'CoQ10 supplement', 'workbook'),
  ('IMG-heart-health-wellbeing-nutrition-wellbeing-nutrition-coq10', 'Capsules', 'workbook'),
  ('IMG-heart-health-wellbeing-nutrition-wellbeing-nutrition-coq10', 'Image Needs Review', 'workbook'),
  ('IMG-heart-health-wellbeing-nutrition-wellbeing-nutrition-coq10', 'Manual Check', 'workbook'),
  ('IMG-heart-health-healthkart-healthkart-coq10-supplement', 'CoQ10 supplement', 'workbook'),
  ('IMG-heart-health-healthkart-healthkart-coq10-supplement', 'Capsules', 'workbook'),
  ('IMG-heart-health-healthkart-healthkart-coq10-supplement', 'Image Needs Review', 'workbook'),
  ('IMG-heart-health-healthkart-healthkart-coq10-supplement', 'Manual Check', 'workbook'),
  ('IMG-heart-health-kapiva-kapiva-bp-care-juice', 'Ayurvedic heart product', 'workbook'),
  ('IMG-heart-health-kapiva-kapiva-bp-care-juice', 'Juice', 'workbook'),
  ('IMG-heart-health-kapiva-kapiva-bp-care-juice', 'Image Needs Review', 'workbook'),
  ('IMG-heart-health-kapiva-kapiva-bp-care-juice', 'Manual Check', 'workbook'),
  ('IMG-heart-health-kapiva-kapiva-cholest-fit-juice', 'Ayurvedic heart product', 'workbook'),
  ('IMG-heart-health-kapiva-kapiva-cholest-fit-juice', 'Juice', 'workbook'),
  ('IMG-heart-health-kapiva-kapiva-cholest-fit-juice', 'Image Needs Review', 'workbook'),
  ('IMG-heart-health-kapiva-kapiva-cholest-fit-juice', 'Manual Check', 'workbook'),
  ('IMG-heart-health-organic-india-organic-india-arjuna-capsules', 'Ayurvedic heart product', 'workbook'),
  ('IMG-heart-health-organic-india-organic-india-arjuna-capsules', 'Capsules', 'workbook'),
  ('IMG-heart-health-organic-india-organic-india-arjuna-capsules', 'Image Needs Review', 'workbook'),
  ('IMG-heart-health-organic-india-organic-india-arjuna-capsules', 'Manual Check', 'workbook'),
  ('IMG-heart-health-organic-india-organic-india-flaxseed-oil-capsules', 'Plant omega supplement', 'workbook'),
  ('IMG-heart-health-organic-india-organic-india-flaxseed-oil-capsules', 'Capsules', 'workbook'),
  ('IMG-heart-health-organic-india-organic-india-flaxseed-oil-capsules', 'Image Needs Review', 'workbook'),
  ('IMG-heart-health-organic-india-organic-india-flaxseed-oil-capsules', 'Manual Check', 'workbook'),
  ('IMG-heart-health-dabur-dabur-hridayasava', 'Ayurvedic heart product', 'workbook'),
  ('IMG-heart-health-dabur-dabur-hridayasava', 'Liquid', 'workbook'),
  ('IMG-heart-health-dabur-dabur-hridayasava', 'Image Needs Review', 'workbook'),
  ('IMG-heart-health-dabur-dabur-hridayasava', 'Manual Check', 'workbook'),
  ('IMG-heart-health-dabur-dabur-arjunarishta', 'Ayurvedic heart product', 'workbook'),
  ('IMG-heart-health-dabur-dabur-arjunarishta', 'Liquid', 'workbook'),
  ('IMG-heart-health-dabur-dabur-arjunarishta', 'Image Needs Review', 'workbook'),
  ('IMG-heart-health-dabur-dabur-arjunarishta', 'Manual Check', 'workbook'),
  ('IMG-heart-health-dabur-dabur-arjuna-tablet', 'Ayurvedic heart product', 'workbook'),
  ('IMG-heart-health-dabur-dabur-arjuna-tablet', 'Tablet', 'workbook'),
  ('IMG-heart-health-dabur-dabur-arjuna-tablet', 'Image Needs Review', 'workbook'),
  ('IMG-heart-health-dabur-dabur-arjuna-tablet', 'Manual Check', 'workbook'),
  ('IMG-heart-health-himalaya-himalaya-abana-tablet', 'Ayurvedic heart product', 'workbook'),
  ('IMG-heart-health-himalaya-himalaya-abana-tablet', 'Tablet', 'workbook'),
  ('IMG-heart-health-himalaya-himalaya-abana-tablet', 'Image Needs Review', 'workbook'),
  ('IMG-heart-health-himalaya-himalaya-abana-tablet', 'Manual Check', 'workbook'),
  ('IMG-heart-health-himalaya-himalaya-garlic-pearls', 'Herbal supplement', 'workbook'),
  ('IMG-heart-health-himalaya-himalaya-garlic-pearls', 'Pearls', 'workbook'),
  ('IMG-heart-health-himalaya-himalaya-garlic-pearls', 'Image Needs Review', 'workbook'),
  ('IMG-heart-health-himalaya-himalaya-garlic-pearls', 'Manual Check', 'workbook'),
  ('IMG-heart-health-omron-omron-hem-7120-blood-pressure-monitor', 'BP monitoring device', 'workbook'),
  ('IMG-heart-health-omron-omron-hem-7120-blood-pressure-monitor', 'Upper arm monitor', 'workbook'),
  ('IMG-heart-health-omron-omron-hem-7120-blood-pressure-monitor', 'Image Needs Review', 'workbook'),
  ('IMG-heart-health-omron-omron-hem-7120-blood-pressure-monitor', 'Manual Check', 'workbook')
) as v(source_product_id, label, tag_type) join products p on p.source_product_id=v.source_product_id on conflict (product_id, label) do nothing;
